-- #######################################################################################
-- ####   AUDIT TABLE CREATION   ##########################################################
-- #######################################################################################

CREATE OR REPLACE TABLE ECOM_DEV_DB.AUDIT.AUDIT_PIPELINE_RUNS (
    AUDIT_RUN_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PIPELINE_NAME VARCHAR,
    PIPELINE_LAYER VARCHAR,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    STATUS VARCHAR,
    TOTAL_ROWS_PROCESSED INT,
    TOTAL_ROWS_INSERTED INT,
    TOTAL_ROWS_UPDATED INT,
    TOTAL_ROWS_REJECTED INT,
    EXECUTED_BY VARCHAR,
    ERROR_MESSAGE VARCHAR,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TABLE ECOM_DEV_DB.AUDIT.AUDIT_TABLE_LOADS (
    TABLE_LOAD_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PIPELINE_NAME VARCHAR,
    SOURCE_TABLE VARCHAR,
    TARGET_TABLE VARCHAR,
    LOAD_TYPE VARCHAR,
    ROWS_READ INT,
    ROWS_INSERTED INT,
    ROWS_UPDATED INT,
    ROWS_DELETED INT,
    ROWS_REJECTED INT,
    LOAD_START_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LOAD_END_TIME TIMESTAMP,
    STATUS VARCHAR,
    ERROR_MESSAGE VARCHAR
);

CREATE OR REPLACE TABLE ECOM_DEV_DB.AUDIT.AUDIT_SQL_QUERY_LOG (
    QUERY_AUDIT_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PIPELINE_NAME VARCHAR,
    QUERY_TEXT VARCHAR,
    EXECUTION_START TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EXECUTION_END TIMESTAMP,
    STATUS VARCHAR,
    ROWS_AFFECTED INT,
    ERROR_MESSAGE VARCHAR
);

CREATE OR REPLACE TABLE ECOM_DEV_DB.AUDIT.AUDIT_FILE_INGESTION (
    FILE_AUDIT_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FILE_NAME VARCHAR,
    STAGE_NAME VARCHAR,
    FILE_SIZE_BYTES NUMBER,
    ROW_COUNT INT,
    LOAD_STATUS VARCHAR,
    LOAD_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ERROR_COUNT INT,
    ERROR_MESSAGE VARCHAR
);