-- =====================================================================
-- GOLD LAYER
-- FINAL PRODUCTION-STYLE STAR SCHEMA
-- CLEAN -> GOLD
-- =====================================================================

-- #####################################################################
-- DIMENSION TABLE LOADS
-- #####################################################################

-- DIM_CUSTOMERS
INSERT INTO ECOM_DEV_DB.GOLD.DIM_CUSTOMERS
(
    CUSTOMER_ID,
    NAME,
    EMAIL,
    PHONE,
    COUNTRY_CODE,
    CREATED_AT
)
SELECT
    CUSTOMER_ID,
    NAME,
    EMAIL,
    PHONE,
    COUNTRY_CODE,
    CREATED_AT
FROM ECOM_DEV_DB.CLEAN.CUSTOMERS_CLEAN;

-- DIM_PRODUCTS
INSERT INTO ECOM_DEV_DB.GOLD.DIM_PRODUCTS
(
    PRODUCT_ID,
    NAME,
    CATEGORY,
    PRICE,
    CURRENCY,
    STOCK_QUANTITY,
    SUPPLIER_ID
)
SELECT
    PRODUCT_ID,
    NAME,
    CATEGORY,
    PRICE,
    CURRENCY,
    STOCK_QUANTITY,
    SUPPLIER_ID
FROM ECOM_DEV_DB.CLEAN.PRODUCTS_CLEAN;

-- DIM_EMPLOYEES
INSERT INTO ECOM_DEV_DB.GOLD.DIM_EMPLOYEES
(
    EMPLOYEE_ID,
    NAME,
    ROLE,
    DEPARTMENT,
    COUNTRY,
    HIRED_DATE
)
SELECT
    EMPLOYEE_ID,
    NAME,
    ROLE,
    DEPARTMENT,
    COUNTRY,
    HIRED_DATE
FROM ECOM_DEV_DB.CLEAN.EMPLOYEES_CLEAN;

-- DIM_DATE
WITH DATE_GENERATOR AS (
    SELECT DATEADD(DAY, SEQ4(), '2020-01-01') AS FULL_DATE
    FROM TABLE(GENERATOR(ROWCOUNT => 6000))
)
INSERT INTO ECOM_DEV_DB.GOLD.DIM_DATE
(
    DATE_KEY,
    FULL_DATE,
    DAY_NUMBER,
    MONTH_NUMBER,
    MONTH_NAME,
    QUARTER_NUMBER,
    YEAR_NUMBER,
    DAY_NAME
)
SELECT
    TO_NUMBER(TO_CHAR(FULL_DATE, 'YYYYMMDD')) AS DATE_KEY,
    FULL_DATE,
    DAY(FULL_DATE) AS DAY_NUMBER,
    MONTH(FULL_DATE) AS MONTH_NUMBER,
    MONTHNAME(FULL_DATE) AS MONTH_NAME,
    QUARTER(FULL_DATE) AS QUARTER_NUMBER,
    YEAR(FULL_DATE) AS YEAR_NUMBER,
    DAYNAME(FULL_DATE) AS DAY_NAME
FROM DATE_GENERATOR
WHERE FULL_DATE <= '2035-12-31';
-- =====================================================================
-- FACT_ORDERS
-- =====================================================================
INSERT INTO ECOM_DEV_DB.GOLD.FACT_ORDERS
(
    ORDER_ID,
    DIM_CUSTOMER_KEY,
    DIM_DATE_KEY,
    TOTAL_AMOUNT,
    STATUS
)
SELECT
    O.ORDER_ID,
    DC.DIM_CUSTOMER_KEY,
    DD.DATE_KEY,
    O.TOTAL_AMOUNT,
    O.STATUS
FROM ECOM_DEV_DB.CLEAN.ORDERS_CLEAN O
INNER JOIN ECOM_DEV_DB.GOLD.DIM_CUSTOMERS DC
    ON O.CUSTOMER_ID = DC.CUSTOMER_ID
INNER JOIN ECOM_DEV_DB.GOLD.DIM_DATE DD
    ON O.ORDER_DATE = DD.FULL_DATE;

-- =====================================================================
-- FACT_ORDER_PRODUCTS
-- =====================================================================
INSERT INTO ECOM_DEV_DB.GOLD.FACT_ORDER_PRODUCTS
(
    FACT_ORDER_KEY,
    DIM_PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    LINE_AMOUNT
)
SELECT
    FO.FACT_ORDER_KEY,
    DP.DIM_PRODUCT_KEY,
    OP.QUANTITY,
    OP.UNIT_PRICE,
    OP.QUANTITY * OP.UNIT_PRICE AS LINE_AMOUNT
FROM ECOM_DEV_DB.CLEAN.ORDER_PRODUCTS_CLEAN OP
INNER JOIN ECOM_DEV_DB.GOLD.FACT_ORDERS FO
    ON OP.ORDER_ID = FO.ORDER_ID
INNER JOIN ECOM_DEV_DB.GOLD.DIM_PRODUCTS DP
    ON OP.PRODUCT_ID = DP.PRODUCT_ID;

-- =====================================================================
-- FACT_PAYMENTS
-- =====================================================================
INSERT INTO ECOM_DEV_DB.GOLD.FACT_PAYMENTS
(
    PAYMENT_ID,
    DIM_DATE_KEY,
    PAYMENT_METHOD,
    AMOUNT,
    CURRENCY
)
SELECT
    P.PAYMENT_ID,
    DD.DATE_KEY,
    P.PAYMENT_METHOD,
    P.AMOUNT,
    P.CURRENCY
FROM ECOM_DEV_DB.CLEAN.PAYMENTS_CLEAN P
INNER JOIN ECOM_DEV_DB.GOLD.DIM_DATE DD
    ON P.PAYMENT_DATE = DD.FULL_DATE;

-- =====================================================================
-- FACT_SHIPMENTS
-- =====================================================================
INSERT INTO ECOM_DEV_DB.GOLD.FACT_SHIPMENTS
(
    SHIPMENT_ID,
    SHIP_DATE_KEY,
    DELIVERY_DATE_KEY,
    CARRIER,
    STATUS,
    SHIP_DATE,
    DELIVERY_DATE,
    DELIVERY_DAYS
)
SELECT
    S.SHIPMENT_ID,
    SD.DATE_KEY AS SHIP_DATE_KEY,
    DD.DATE_KEY AS DELIVERY_DATE_KEY,
    S.CARRIER,
    S.STATUS,
    S.SHIP_DATE,
    S.DELIVERY_DATE,
    DATEDIFF(DAY, S.SHIP_DATE, S.DELIVERY_DATE) AS DELIVERY_DAYS
FROM ECOM_DEV_DB.CLEAN.SHIPMENTS_CLEAN S
INNER JOIN ECOM_DEV_DB.GOLD.DIM_DATE SD
    ON S.SHIP_DATE = SD.FULL_DATE
INNER JOIN ECOM_DEV_DB.GOLD.DIM_DATE DD
    ON S.DELIVERY_DATE = DD.FULL_DATE;