-- =================================================================================================================================
-- LOADING FROM RAW TO STAGE - CUSTOMERS
-- =================================================================================================================================

-- STEP 1: REJECTED RECORDS TO DQ
INSERT INTO ECOM_DEV_DB.DQ.DQ_ERROR_LOG
(
    PIPELINE_NAME,
    LAYER_NAME,
    TABLE_NAME,
    BUSINESS_KEY,
    ERROR_TYPE,
    ERROR_MESSAGE,
    LOAD_TIMESTAMP,
    RAW_RECORD
)
SELECT
    'CUSTOMER_PIPELINE',
    'RAW_TO_STAGE',
    'RAW_CUSTOMERS',
    RC.CUSTOMER_ID,
    CASE
        WHEN RC.CUSTOMER_ID IS NULL THEN 'NULL_CUSTOMER_ID'
        WHEN TRY_CAST(TRIM(RC.CUSTOMER_ID) AS INT) <= 0 THEN 'INVALID_CUSTOMER_ID'
        WHEN RC.NAME IS NULL OR TRIM(RC.NAME) = '' THEN 'INVALID_NAME'
        WHEN RC.EMAIL IS NULL OR TRIM(RC.EMAIL) = '' THEN 'NULL_EMAIL'
        WHEN NOT REGEXP_LIKE(LOWER(REPLACE(TRIM(RC.EMAIL),' ','')),'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN 'INVALID_EMAIL'
        WHEN RC.PHONE IS NULL OR TRIM(RC.PHONE) = '' THEN 'NULL_PHONE'
        WHEN RC.COUNTRY IS NULL OR TRIM(RC.COUNTRY) = '' THEN 'NULL_COUNTRY'
        WHEN CM.COUNTRY_CODE IS NULL THEN 'INVALID_COUNTRY'
        WHEN RC.CREATED_AT IS NULL OR TRIM(RC.CREATED_AT) = '' THEN 'NULL_CREATED_DATE'
        WHEN TRY_TO_DATE(TRIM(RC.CREATED_AT),'DD-MM-YYYY') IS NULL THEN 'INVALID_DATE'
        WHEN TRY_TO_DATE(TRIM(RC.CREATED_AT),'DD-MM-YYYY') > CURRENT_DATE() THEN 'FUTURE_DATE'
    END AS ERROR_TYPE,
    CASE
        WHEN RC.CUSTOMER_ID IS NULL THEN 'CUSTOMER ID IS NULL'
        WHEN TRY_CAST(TRIM(RC.CUSTOMER_ID) AS INT) <= 0 THEN 'CUSTOMER ID MUST BE GREATER THAN ZERO'
        WHEN RC.NAME IS NULL OR TRIM(RC.NAME) = '' THEN 'CUSTOMER NAME IS NULL OR BLANK'
        WHEN RC.EMAIL IS NULL OR TRIM(RC.EMAIL) = '' THEN 'EMAIL IS NULL OR BLANK'
        WHEN NOT REGEXP_LIKE(LOWER(REPLACE(TRIM(RC.EMAIL),' ','')),'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN 'EMAIL FORMAT IS INVALID'
        WHEN RC.PHONE IS NULL OR TRIM(RC.PHONE) = '' THEN 'PHONE NUMBER IS NULL OR BLANK'
        WHEN RC.COUNTRY IS NULL OR TRIM(RC.COUNTRY) = '' THEN 'COUNTRY IS NULL OR BLANK'
        WHEN CM.COUNTRY_CODE IS NULL THEN 'COUNTRY NOT FOUND IN COUNTRY_MASTER'
        WHEN RC.CREATED_AT IS NULL OR TRIM(RC.CREATED_AT) = '' THEN 'CREATED DATE IS NULL OR BLANK'
        WHEN TRY_TO_DATE(TRIM(RC.CREATED_AT),'DD-MM-YYYY') IS NULL THEN 'INVALID DATE FORMAT'
        WHEN TRY_TO_DATE(TRIM(RC.CREATED_AT),'DD-MM-YYYY') > CURRENT_DATE() THEN 'DATE CANNOT BE IN THE FUTURE'
    END AS ERROR_MESSAGE,
    CURRENT_TIMESTAMP(),
    OBJECT_CONSTRUCT(*)
FROM ECOM_DEV_DB.RAW.RAW_CUSTOMERS RC
LEFT JOIN ECOM_DEV_DB.REFERENCE.COUNTRY_MASTER CM
    ON UPPER(TRIM(RC.COUNTRY)) = UPPER(TRIM(CM.COUNTRY_NAME))
WHERE
    RC.CUSTOMER_ID IS NULL
    OR TRY_CAST(TRIM(RC.CUSTOMER_ID) AS INT) <= 0
    OR RC.NAME IS NULL OR TRIM(RC.NAME) = ''
    OR RC.EMAIL IS NULL OR TRIM(RC.EMAIL) = ''
    OR NOT REGEXP_LIKE(LOWER(REPLACE(TRIM(RC.EMAIL),' ','')),'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
    OR RC.PHONE IS NULL OR TRIM(RC.PHONE) = ''
    OR RC.COUNTRY IS NULL OR TRIM(RC.COUNTRY) = ''
    OR CM.COUNTRY_CODE IS NULL
    OR RC.CREATED_AT IS NULL OR TRIM(RC.CREATED_AT) = ''
    OR TRY_TO_DATE(TRIM(RC.CREATED_AT),'DD-MM-YYYY') IS NULL
    OR TRY_TO_DATE(TRIM(RC.CREATED_AT),'DD-MM-YYYY') > CURRENT_DATE();

-- STEP 2: CLEAN DATA TO STAGE
INSERT INTO ECOM_DEV_DB.STAGE.STAGE_CUSTOMERS
(
    CUSTOMER_ID,
    NAME,
    EMAIL,
    PHONE,
    COUNTRY,
    CREATED_AT
)
SELECT
    TRY_CAST(TRIM(RC.CUSTOMER_ID) AS INT) AS CUSTOMER_ID,
    UPPER(TRIM(RC.NAME)) AS NAME,
    LOWER(REPLACE(TRIM(RC.EMAIL), ' ', '')) AS EMAIL,
    REGEXP_REPLACE(RC.PHONE, '[^0-9+]', '') AS PHONE,
    CM.COUNTRY_CODE AS COUNTRY,
    TRY_TO_DATE(TRIM(RC.CREATED_AT),'DD-MM-YYYY') AS CREATED_AT
FROM ECOM_DEV_DB.RAW.RAW_CUSTOMERS RC
INNER JOIN ECOM_DEV_DB.REFERENCE.COUNTRY_MASTER CM
    ON UPPER(TRIM(RC.COUNTRY)) = UPPER(TRIM(CM.COUNTRY_NAME))
WHERE
    RC.CUSTOMER_ID IS NOT NULL
    AND TRY_CAST(TRIM(RC.CUSTOMER_ID) AS INT) > 0
    AND RC.NAME IS NOT NULL AND TRIM(RC.NAME) <> ''
    AND RC.EMAIL IS NOT NULL AND TRIM(RC.EMAIL) <> ''
    AND REGEXP_LIKE(LOWER(REPLACE(TRIM(RC.EMAIL), ' ', '')),'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
    AND RC.PHONE IS NOT NULL AND TRIM(RC.PHONE) <> ''
    AND RC.COUNTRY IS NOT NULL AND TRIM(RC.COUNTRY) <> ''
    AND RC.CREATED_AT IS NOT NULL AND TRIM(RC.CREATED_AT) <> ''
    AND TRY_TO_DATE(TRIM(RC.CREATED_AT),'DD-MM-YYYY') IS NOT NULL
    AND TRY_TO_DATE(TRIM(RC.CREATED_AT),'DD-MM-YYYY') <= CURRENT_DATE();

    -- ============================================================================================================================
-- LOADING FROM RAW TO STAGE : ORDERS
-- ============================================================================================================================

-- STEP 1 : REJECTED RECORDS TO DQ
INSERT INTO ECOM_DEV_DB.DQ.DQ_ERROR_LOG
(
    PIPELINE_NAME,
    LAYER_NAME,
    TABLE_NAME,
    BUSINESS_KEY,
    ERROR_TYPE,
    ERROR_MESSAGE,
    LOAD_TIMESTAMP,
    RAW_RECORD
)
SELECT
    'ORDER_PIPELINE',
    'RAW_TO_STAGE',
    'RAW_ORDERS',
    TRY_CAST(TRIM(RO.ORDER_ID) AS INT),
    CASE
        WHEN RO.ORDER_ID IS NULL OR TRIM(RO.ORDER_ID) = '' THEN 'NULL_ORDER_ID'
        WHEN TRY_CAST(TRIM(RO.ORDER_ID) AS INT) <= 0 THEN 'INVALID_ORDER_ID'
        WHEN RO.CUSTOMER_ID IS NULL OR TRIM(RO.CUSTOMER_ID) = '' THEN 'NULL_CUSTOMER_ID'
        WHEN TRY_CAST(TRIM(RO.CUSTOMER_ID) AS INT) <= 0 THEN 'INVALID_CUSTOMER_ID'
        WHEN RO.ORDER_DATE IS NULL OR TRIM(RO.ORDER_DATE) = '' THEN 'NULL_ORDER_DATE'
        WHEN TRY_TO_DATE(TRIM(RO.ORDER_DATE),'DD-MM-YYYY') IS NULL THEN 'INVALID_ORDER_DATE'
        WHEN TRY_TO_DATE(TRIM(RO.ORDER_DATE),'DD-MM-YYYY') > CURRENT_DATE() THEN 'FUTURE_ORDER_DATE'
        WHEN RO.STATUS IS NULL OR TRIM(RO.STATUS) = '' THEN 'NULL_STATUS'
        WHEN OSM.STATUS_NAME IS NULL THEN 'INVALID_STATUS'
        WHEN RO.TOTAL_AMOUNT IS NULL OR TRIM(RO.TOTAL_AMOUNT) = '' THEN 'NULL_TOTAL_AMOUNT'
        WHEN TRY_CAST(TRIM(RO.TOTAL_AMOUNT) AS DECIMAL(18,2)) IS NULL THEN 'INVALID_TOTAL_AMOUNT'
        WHEN TRY_CAST(TRIM(RO.TOTAL_AMOUNT) AS DECIMAL(18,2)) < 0 THEN 'NEGATIVE_TOTAL_AMOUNT'
        WHEN RO.PAYMENT_ID IS NULL OR TRIM(RO.PAYMENT_ID) = '' THEN 'NULL_PAYMENT_ID'
        WHEN TRY_CAST(TRIM(RO.PAYMENT_ID) AS INT) <= 0 THEN 'INVALID_PAYMENT_ID'
        WHEN RO.SHIPMENT_ID IS NULL OR TRIM(RO.SHIPMENT_ID) = '' THEN 'NULL_SHIPMENT_ID'
        WHEN TRY_CAST(TRIM(RO.SHIPMENT_ID) AS INT) <= 0 THEN 'INVALID_SHIPMENT_ID'
    END AS ERROR_TYPE,
    CASE
        WHEN RO.ORDER_ID IS NULL OR TRIM(RO.ORDER_ID) = '' THEN 'ORDER ID IS NULL OR BLANK'
        WHEN TRY_CAST(TRIM(RO.ORDER_ID) AS INT) <= 0 THEN 'ORDER ID MUST BE GREATER THAN ZERO'
        WHEN RO.CUSTOMER_ID IS NULL OR TRIM(RO.CUSTOMER_ID) = '' THEN 'CUSTOMER ID IS NULL OR BLANK'
        WHEN TRY_CAST(TRIM(RO.CUSTOMER_ID) AS INT) <= 0 THEN 'CUSTOMER ID MUST BE GREATER THAN ZERO'
        WHEN RO.ORDER_DATE IS NULL OR TRIM(RO.ORDER_DATE) = '' THEN 'ORDER DATE IS NULL OR BLANK'
        WHEN TRY_TO_DATE(TRIM(RO.ORDER_DATE),'DD-MM-YYYY') IS NULL THEN 'ORDER DATE FORMAT IS INVALID'
        WHEN TRY_TO_DATE(TRIM(RO.ORDER_DATE),'DD-MM-YYYY') > CURRENT_DATE() THEN 'ORDER DATE CANNOT BE IN FUTURE'
        WHEN RO.STATUS IS NULL OR TRIM(RO.STATUS) = '' THEN 'ORDER STATUS IS NULL OR BLANK'
        WHEN OSM.STATUS_NAME IS NULL THEN 'STATUS NOT FOUND IN ORDER_STATUS_MASTER'
        WHEN RO.TOTAL_AMOUNT IS NULL OR TRIM(RO.TOTAL_AMOUNT) = '' THEN 'TOTAL AMOUNT IS NULL OR BLANK'
        WHEN TRY_CAST(TRIM(RO.TOTAL_AMOUNT) AS DECIMAL(18,2)) IS NULL THEN 'TOTAL AMOUNT IS NOT NUMERIC'
        WHEN TRY_CAST(TRIM(RO.TOTAL_AMOUNT) AS DECIMAL(18,2)) < 0 THEN 'TOTAL AMOUNT CANNOT BE NEGATIVE'
        WHEN RO.PAYMENT_ID IS NULL OR TRIM(RO.PAYMENT_ID) = '' THEN 'PAYMENT ID IS NULL OR BLANK'
        WHEN TRY_CAST(TRIM(RO.PAYMENT_ID) AS INT) <= 0 THEN 'PAYMENT ID MUST BE GREATER THAN ZERO'
        WHEN RO.SHIPMENT_ID IS NULL OR TRIM(RO.SHIPMENT_ID) = '' THEN 'SHIPMENT ID IS NULL OR BLANK'
        WHEN TRY_CAST(TRIM(RO.SHIPMENT_ID) AS INT) <= 0 THEN 'SHIPMENT ID MUST BE GREATER THAN ZERO'
    END AS ERROR_MESSAGE,
    CURRENT_TIMESTAMP(),
    OBJECT_CONSTRUCT(*)
FROM ECOM_DEV_DB.RAW.RAW_ORDERS RO
LEFT JOIN ECOM_DEV_DB.REFERENCE.ORDER_STATUS_MASTER OSM
    ON UPPER(TRIM(RO.STATUS)) = UPPER(TRIM(OSM.STATUS_NAME))
WHERE
    RO.ORDER_ID IS NULL OR TRIM(RO.ORDER_ID) = '' OR TRY_CAST(TRIM(RO.ORDER_ID) AS INT) <= 0
    OR RO.CUSTOMER_ID IS NULL OR TRIM(RO.CUSTOMER_ID) = '' OR TRY_CAST(TRIM(RO.CUSTOMER_ID) AS INT) <= 0
    OR RO.ORDER_DATE IS NULL OR TRIM(RO.ORDER_DATE) = '' OR TRY_TO_DATE(TRIM(RO.ORDER_DATE),'DD-MM-YYYY') IS NULL OR TRY_TO_DATE(TRIM(RO.ORDER_DATE),'DD-MM-YYYY') > CURRENT_DATE()
    OR RO.STATUS IS NULL OR TRIM(RO.STATUS) = '' OR OSM.STATUS_NAME IS NULL
    OR RO.TOTAL_AMOUNT IS NULL OR TRIM(RO.TOTAL_AMOUNT) = '' OR TRY_CAST(TRIM(RO.TOTAL_AMOUNT) AS DECIMAL(18,2)) IS NULL OR TRY_CAST(TRIM(RO.TOTAL_AMOUNT) AS DECIMAL(18,2)) < 0
    OR RO.PAYMENT_ID IS NULL OR TRIM(RO.PAYMENT_ID) = '' OR TRY_CAST(TRIM(RO.PAYMENT_ID) AS INT) <= 0
    OR RO.SHIPMENT_ID IS NULL OR TRIM(RO.SHIPMENT_ID) = '' OR TRY_CAST(TRIM(RO.SHIPMENT_ID) AS INT) <= 0;

-- STEP 2 : CLEAN DATA TO STAGE
INSERT INTO ECOM_DEV_DB.STAGE.STAGE_ORDERS
(
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_DATE,
    STATUS,
    TOTAL_AMOUNT,
    PAYMENT_ID,
    SHIPMENT_ID
)
SELECT
    TRY_CAST(TRIM(RO.ORDER_ID) AS INT) AS ORDER_ID,
    TRY_CAST(TRIM(RO.CUSTOMER_ID) AS INT) AS CUSTOMER_ID,
    TRY_TO_DATE(TRIM(RO.ORDER_DATE),'DD-MM-YYYY') AS ORDER_DATE,
    OSM.STATUS_NAME AS STATUS,
    TRY_CAST(TRIM(RO.TOTAL_AMOUNT) AS DECIMAL(18,2)) AS TOTAL_AMOUNT,
    TRY_CAST(TRIM(RO.PAYMENT_ID) AS INT) AS PAYMENT_ID,
    TRY_CAST(TRIM(RO.SHIPMENT_ID) AS INT) AS SHIPMENT_ID
FROM ECOM_DEV_DB.RAW.RAW_ORDERS RO
INNER JOIN ECOM_DEV_DB.REFERENCE.ORDER_STATUS_MASTER OSM
    ON UPPER(TRIM(RO.STATUS)) = UPPER(TRIM(OSM.STATUS_NAME))
WHERE
    RO.ORDER_ID IS NOT NULL AND TRIM(RO.ORDER_ID) <> '' AND TRY_CAST(TRIM(RO.ORDER_ID) AS INT) > 0
    AND RO.CUSTOMER_ID IS NOT NULL AND TRIM(RO.CUSTOMER_ID) <> '' AND TRY_CAST(TRIM(RO.CUSTOMER_ID) AS INT) > 0
    AND RO.ORDER_DATE IS NOT NULL AND TRIM(RO.ORDER_DATE) <> '' AND TRY_TO_DATE(TRIM(RO.ORDER_DATE),'DD-MM-YYYY') IS NOT NULL AND TRY_TO_DATE(TRIM(RO.ORDER_DATE),'DD-MM-YYYY') <= CURRENT_DATE()
    AND RO.STATUS IS NOT NULL AND TRIM(RO.STATUS) <> ''
    AND RO.TOTAL_AMOUNT IS NOT NULL AND TRIM(RO.TOTAL_AMOUNT) <> '' AND TRY_CAST(TRIM(RO.TOTAL_AMOUNT) AS DECIMAL(18,2)) >= 0
    AND RO.PAYMENT_ID IS NOT NULL AND TRIM(RO.PAYMENT_ID) <> '' AND TRY_CAST(TRIM(RO.PAYMENT_ID) AS INT) > 0
    AND RO.SHIPMENT_ID IS NOT NULL AND TRIM(RO.SHIPMENT_ID) <> '' AND TRY_CAST(TRIM(RO.SHIPMENT_ID) AS INT) > 0

;
-- ============================================================================================================================
-- LOADING FROM RAW TO STAGE : PAYMENTS
-- ============================================================================================================================

-- STEP 1 : REJECTED RECORDS TO DQ
INSERT INTO ECOM_DEV_DB.DQ.DQ_ERROR_LOG
(
    PIPELINE_NAME,
    LAYER_NAME,
    TABLE_NAME,
    BUSINESS_KEY,
    ERROR_TYPE,
    ERROR_MESSAGE,
    LOAD_TIMESTAMP,
    RAW_RECORD
)
SELECT
    'PAYMENT_PIPELINE',
    'RAW_TO_STAGE',
    'RAW_PAYMENTS',
    TRY_CAST(TRIM(RP.PAYMENT_ID) AS INT),
    CASE
        WHEN RP.PAYMENT_ID IS NULL OR TRIM(RP.PAYMENT_ID) = '' THEN 'NULL_PAYMENT_ID'
        WHEN TRY_CAST(TRIM(RP.PAYMENT_ID) AS INT) <= 0 THEN 'INVALID_PAYMENT_ID'
        WHEN RP.ORDER_ID IS NULL OR TRIM(RP.ORDER_ID) = '' THEN 'NULL_ORDER_ID'
        WHEN TRY_CAST(TRIM(RP.ORDER_ID) AS INT) <= 0 THEN 'INVALID_ORDER_ID'
        WHEN RP.PAYMENT_METHOD IS NULL OR TRIM(RP.PAYMENT_METHOD) = '' THEN 'NULL_PAYMENT_METHOD'
        WHEN PMM.PAYMENT_METHOD_NAME IS NULL THEN 'INVALID_PAYMENT_METHOD'
        WHEN RP.PAYMENT_DATE IS NULL OR TRIM(RP.PAYMENT_DATE) = '' THEN 'NULL_PAYMENT_DATE'
        WHEN TRY_TO_DATE(TRIM(RP.PAYMENT_DATE),'DD-MM-YYYY') IS NULL THEN 'INVALID_PAYMENT_DATE'
        WHEN TRY_TO_DATE(TRIM(RP.PAYMENT_DATE),'DD-MM-YYYY') > CURRENT_DATE() THEN 'FUTURE_PAYMENT_DATE'
        WHEN RP.AMOUNT IS NULL OR TRIM(RP.AMOUNT) = '' THEN 'NULL_AMOUNT'
        WHEN TRY_CAST(TRIM(RP.AMOUNT) AS DECIMAL(18,2)) IS NULL THEN 'INVALID_AMOUNT'
        WHEN TRY_CAST(TRIM(RP.AMOUNT) AS DECIMAL(18,2)) < 0 THEN 'NEGATIVE_AMOUNT'
        WHEN RP.CURRENCY IS NULL OR TRIM(RP.CURRENCY) = '' THEN 'NULL_CURRENCY'
        WHEN CM.CURRENCY_CODE IS NULL THEN 'INVALID_CURRENCY'
    END AS ERROR_TYPE,
    CASE
        WHEN RP.PAYMENT_ID IS NULL OR TRIM(RP.PAYMENT_ID) = '' THEN 'PAYMENT ID IS NULL OR BLANK'
        WHEN TRY_CAST(TRIM(RP.PAYMENT_ID) AS INT) <= 0 THEN 'PAYMENT ID MUST BE GREATER THAN ZERO'
        WHEN RP.ORDER_ID IS NULL OR TRIM(RP.ORDER_ID) = '' THEN 'ORDER ID IS NULL OR BLANK'
        WHEN TRY_CAST(TRIM(RP.ORDER_ID) AS INT) <= 0 THEN 'ORDER ID MUST BE GREATER THAN ZERO'
        WHEN RP.PAYMENT_METHOD IS NULL OR TRIM(RP.PAYMENT_METHOD) = '' THEN 'PAYMENT METHOD IS NULL OR BLANK'
        WHEN PMM.PAYMENT_METHOD_NAME IS NULL THEN 'PAYMENT METHOD NOT FOUND IN PAYMENT_METHOD_MASTER'
        WHEN RP.PAYMENT_DATE IS NULL OR TRIM(RP.PAYMENT_DATE) = '' THEN 'PAYMENT DATE IS NULL OR BLANK'
        WHEN TRY_TO_DATE(TRIM(RP.PAYMENT_DATE),'DD-MM-YYYY') IS NULL THEN 'PAYMENT DATE FORMAT IS INVALID'
        WHEN TRY_TO_DATE(TRIM(RP.PAYMENT_DATE),'DD-MM-YYYY') > CURRENT_DATE() THEN 'PAYMENT DATE CANNOT BE IN FUTURE'
        WHEN RP.AMOUNT IS NULL OR TRIM(RP.AMOUNT) = '' THEN 'AMOUNT IS NULL OR BLANK'
        WHEN TRY_CAST(TRIM(RP.AMOUNT) AS DECIMAL(18,2)) IS NULL THEN 'AMOUNT IS NOT NUMERIC'
        WHEN TRY_CAST(TRIM(RP.AMOUNT) AS DECIMAL(18,2)) < 0 THEN 'AMOUNT CANNOT BE NEGATIVE'
        WHEN RP.CURRENCY IS NULL OR TRIM(RP.CURRENCY) = '' THEN 'CURRENCY IS NULL OR BLANK'
        WHEN CM.CURRENCY_CODE IS NULL THEN 'CURRENCY NOT FOUND IN CURRENCY_MASTER'
    END AS ERROR_MESSAGE,
    CURRENT_TIMESTAMP(),
    OBJECT_CONSTRUCT(*)
FROM ECOM_DEV_DB.RAW.RAW_PAYMENTS RP
LEFT JOIN ECOM_DEV_DB.REFERENCE.PAYMENT_METHOD_MASTER PMM
    ON UPPER(TRIM(RP.PAYMENT_METHOD)) = UPPER(TRIM(PMM.PAYMENT_METHOD_NAME))
LEFT JOIN ECOM_DEV_DB.REFERENCE.CURRENCY_MASTER CM
    ON UPPER(TRIM(RP.CURRENCY)) = UPPER(TRIM(CM.CURRENCY_CODE))
WHERE
    RP.PAYMENT_ID IS NULL OR TRIM(RP.PAYMENT_ID) = '' OR TRY_CAST(TRIM(RP.PAYMENT_ID) AS INT) <= 0
    OR RP.ORDER_ID IS NULL OR TRIM(RP.ORDER_ID) = '' OR TRY_CAST(TRIM(RP.ORDER_ID) AS INT) <= 0
    OR RP.PAYMENT_METHOD IS NULL OR TRIM(RP.PAYMENT_METHOD) = '' OR PMM.PAYMENT_METHOD_NAME IS NULL
    OR RP.PAYMENT_DATE IS NULL OR TRIM(RP.PAYMENT_DATE) = '' OR TRY_TO_DATE(TRIM(RP.PAYMENT_DATE),'DD-MM-YYYY') IS NULL OR TRY_TO_DATE(TRIM(RP.PAYMENT_DATE),'DD-MM-YYYY') > CURRENT_DATE()
    OR RP.AMOUNT IS NULL OR TRIM(RP.AMOUNT) = '' OR TRY_CAST(TRIM(RP.AMOUNT) AS DECIMAL(18,2)) IS NULL OR TRY_CAST(TRIM(RP.AMOUNT) AS DECIMAL(18,2)) < 0
    OR RP.CURRENCY IS NULL OR TRIM(RP.CURRENCY) = '' OR CM.CURRENCY_CODE IS NULL;

-- STEP 2 : CLEAN DATA TO STAGE
INSERT INTO ECOM_DEV_DB.STAGE.STAGE_PAYMENTS
(
    PAYMENT_ID,
    ORDER_ID,
    PAYMENT_METHOD,
    PAYMENT_DATE,
    AMOUNT,
    CURRENCY
)
SELECT
    TRY_CAST(TRIM(RP.PAYMENT_ID) AS INT) AS PAYMENT_ID,
    TRY_CAST(TRIM(RP.ORDER_ID) AS INT) AS ORDER_ID,
    PMM.PAYMENT_METHOD_NAME AS PAYMENT_METHOD,
    TRY_TO_DATE(TRIM(RP.PAYMENT_DATE),'DD-MM-YYYY') AS PAYMENT_DATE,
    TRY_CAST(TRIM(RP.AMOUNT) AS DECIMAL(18,2)) AS AMOUNT,
    CM.CURRENCY_CODE AS CURRENCY
FROM ECOM_DEV_DB.RAW.RAW_PAYMENTS RP
INNER JOIN ECOM_DEV_DB.REFERENCE.PAYMENT_METHOD_MASTER PMM
    ON UPPER(TRIM(RP.PAYMENT_METHOD)) = UPPER(TRIM(PMM.PAYMENT_METHOD_NAME))
INNER JOIN ECOM_DEV_DB.REFERENCE.CURRENCY_MASTER CM
    ON UPPER(TRIM(RP.CURRENCY)) = UPPER(TRIM(CM.CURRENCY_CODE))
WHERE
    RP.PAYMENT_ID IS NOT NULL AND TRIM(RP.PAYMENT_ID) <> '' AND TRY_CAST(TRIM(RP.PAYMENT_ID) AS INT) > 0
    AND RP.ORDER_ID IS NOT NULL AND TRIM(RP.ORDER_ID) <> '' AND TRY_CAST(TRIM(RP.ORDER_ID) AS INT) > 0
    AND RP.PAYMENT_METHOD IS NOT NULL AND TRIM(RP.PAYMENT_METHOD) <> ''
    AND RP.PAYMENT_DATE IS NOT NULL AND TRIM(RP.PAYMENT_DATE) <> '' AND TRY_TO_DATE(TRIM(RP.PAYMENT_DATE),'DD-MM-YYYY') IS NOT NULL AND TRY_TO_DATE(TRIM(RP.PAYMENT_DATE),'DD-MM-YYYY') <= CURRENT_DATE()
    AND RP.AMOUNT IS NOT NULL AND TRIM(RP.AMOUNT) <> '' AND TRY_CAST(TRIM(RP.AMOUNT) AS DECIMAL(18,2)) >= 0
    AND RP.CURRENCY IS NOT NULL AND TRIM(RP.CURRENCY) <> '';

    -- ============================================================================================================================
-- LOADING FROM RAW TO STAGE : SHIPMENTS
-- ============================================================================================================================

-- STEP 1 : REJECTED RECORDS TO DQ
INSERT INTO ECOM_DEV_DB.DQ.DQ_ERROR_LOG
(
    PIPELINE_NAME,
    LAYER_NAME,
    TABLE_NAME,
    BUSINESS_KEY,
    ERROR_TYPE,
    ERROR_MESSAGE,
    LOAD_TIMESTAMP,
    RAW_RECORD
)
SELECT
    'SHIPMENT_PIPELINE',
    'RAW_TO_STAGE',
    'RAW_SHIPMENTS',
    TRY_CAST(TRIM(RS.SHIPMENT_ID) AS INT),
    CASE
        WHEN RS.SHIPMENT_ID IS NULL OR TRIM(RS.SHIPMENT_ID) = '' THEN 'NULL_SHIPMENT_ID'
        WHEN TRY_CAST(TRIM(RS.SHIPMENT_ID) AS INT) <= 0 THEN 'INVALID_SHIPMENT_ID'
        WHEN RS.ORDER_ID IS NULL OR TRIM(RS.ORDER_ID) = '' THEN 'NULL_ORDER_ID'
        WHEN TRY_CAST(TRIM(RS.ORDER_ID) AS INT) <= 0 THEN 'INVALID_ORDER_ID'
        WHEN RS.SHIP_DATE IS NULL OR TRIM(RS.SHIP_DATE) = '' THEN 'NULL_SHIP_DATE'
        WHEN TRY_TO_DATE(TRIM(RS.SHIP_DATE),'DD-MM-YYYY') IS NULL THEN 'INVALID_SHIP_DATE'
        WHEN TRY_TO_DATE(TRIM(RS.SHIP_DATE),'DD-MM-YYYY') > CURRENT_DATE() THEN 'FUTURE_SHIP_DATE'
        WHEN RS.DELIVERY_DATE IS NULL OR TRIM(RS.DELIVERY_DATE) = '' THEN 'NULL_DELIVERY_DATE'
        WHEN TRY_TO_DATE(TRIM(RS.DELIVERY_DATE),'DD-MM-YYYY') IS NULL THEN 'INVALID_DELIVERY_DATE'
        WHEN TRY_TO_DATE(TRIM(RS.DELIVERY_DATE),'DD-MM-YYYY') > CURRENT_DATE() THEN 'FUTURE_DELIVERY_DATE'
        WHEN TRY_TO_DATE(TRIM(RS.DELIVERY_DATE),'DD-MM-YYYY') < TRY_TO_DATE(TRIM(RS.SHIP_DATE),'DD-MM-YYYY') THEN 'INVALID_DELIVERY_SEQUENCE'
        WHEN RS.CARRIER IS NULL OR TRIM(RS.CARRIER) = '' THEN 'NULL_CARRIER'
        WHEN SCM.CARRIER_NAME IS NULL THEN 'INVALID_CARRIER'
        WHEN RS.STATUS IS NULL OR TRIM(RS.STATUS) = '' THEN 'NULL_STATUS'
        WHEN SSM.STATUS_NAME IS NULL THEN 'INVALID_STATUS'
    END AS ERROR_TYPE,
    CASE
        WHEN RS.SHIPMENT_ID IS NULL OR TRIM(RS.SHIPMENT_ID) = '' THEN 'SHIPMENT ID IS NULL OR BLANK'
        WHEN TRY_CAST(TRIM(RS.SHIPMENT_ID) AS INT) <= 0 THEN 'SHIPMENT ID MUST BE GREATER THAN ZERO'
        WHEN RS.ORDER_ID IS NULL OR TRIM(RS.ORDER_ID) = '' THEN 'ORDER ID IS NULL OR BLANK'
        WHEN TRY_CAST(TRIM(RS.ORDER_ID) AS INT) <= 0 THEN 'ORDER ID MUST BE GREATER THAN ZERO'
        WHEN RS.SHIP_DATE IS NULL OR TRIM(RS.SHIP_DATE) = '' THEN 'SHIP DATE IS NULL OR BLANK'
        WHEN TRY_TO_DATE(TRIM(RS.SHIP_DATE),'DD-MM-YYYY') IS NULL THEN 'SHIP DATE FORMAT IS INVALID'
        WHEN TRY_TO_DATE(TRIM(RS.SHIP_DATE),'DD-MM-YYYY') > CURRENT_DATE() THEN 'SHIP DATE CANNOT BE IN FUTURE'
        WHEN RS.DELIVERY_DATE IS NULL OR TRIM(RS.DELIVERY_DATE) = '' THEN 'DELIVERY DATE IS NULL OR BLANK'
        WHEN TRY_TO_DATE(TRIM(RS.DELIVERY_DATE),'DD-MM-YYYY') IS NULL THEN 'DELIVERY DATE FORMAT IS INVALID'
        WHEN TRY_TO_DATE(TRIM(RS.DELIVERY_DATE),'DD-MM-YYYY') > CURRENT_DATE() THEN 'DELIVERY DATE CANNOT BE IN FUTURE'
        WHEN TRY_TO_DATE(TRIM(RS.DELIVERY_DATE),'DD-MM-YYYY') < TRY_TO_DATE(TRIM(RS.SHIP_DATE),'DD-MM-YYYY') THEN 'DELIVERY DATE CANNOT BE BEFORE SHIP DATE'
        WHEN RS.CARRIER IS NULL OR TRIM(RS.CARRIER) = '' THEN 'CARRIER IS NULL OR BLANK'
        WHEN SCM.CARRIER_NAME IS NULL THEN 'CARRIER NOT FOUND IN SHIPMENT_CARRIER_MASTER'
        WHEN RS.STATUS IS NULL OR TRIM(RS.STATUS) = '' THEN 'SHIPMENT STATUS IS NULL OR BLANK'
        WHEN SSM.STATUS_NAME IS NULL THEN 'STATUS NOT FOUND IN SHIPMENT_STATUS_MASTER'
    END AS ERROR_MESSAGE,
    CURRENT_TIMESTAMP(),
    OBJECT_CONSTRUCT(*)
FROM ECOM_DEV_DB.RAW.RAW_SHIPMENTS RS
LEFT JOIN ECOM_DEV_DB.REFERENCE.SHIPMENT_CARRIER_MASTER SCM
    ON UPPER(TRIM(RS.CARRIER)) = UPPER(TRIM(SCM.CARRIER_NAME))
LEFT JOIN ECOM_DEV_DB.REFERENCE.SHIPMENT_STATUS_MASTER SSM
    ON UPPER(TRIM(RS.STATUS)) = UPPER(TRIM(SSM.STATUS_NAME))
WHERE
    RS.SHIPMENT_ID IS NULL OR TRIM(RS.SHIPMENT_ID) = '' OR TRY_CAST(TRIM(RS.SHIPMENT_ID) AS INT) <= 0
    OR RS.ORDER_ID IS NULL OR TRIM(RS.ORDER_ID) = '' OR TRY_CAST(TRIM(RS.ORDER_ID) AS INT) <= 0
    OR RS.SHIP_DATE IS NULL OR TRIM(RS.SHIP_DATE) = '' OR TRY_TO_DATE(TRIM(RS.SHIP_DATE),'DD-MM-YYYY') IS NULL OR TRY_TO_DATE(TRIM(RS.SHIP_DATE),'DD-MM-YYYY') > CURRENT_DATE()
    OR RS.DELIVERY_DATE IS NULL OR TRIM(RS.DELIVERY_DATE) = '' OR TRY_TO_DATE(TRIM(RS.DELIVERY_DATE),'DD-MM-YYYY') IS NULL OR TRY_TO_DATE(TRIM(RS.DELIVERY_DATE),'DD-MM-YYYY') > CURRENT_DATE()
    OR TRY_TO_DATE(TRIM(RS.DELIVERY_DATE),'DD-MM-YYYY') < TRY_TO_DATE(TRIM(RS.SHIP_DATE),'DD-MM-YYYY')
    OR RS.CARRIER IS NULL OR TRIM(RS.CARRIER) = '' OR SCM.CARRIER_NAME IS NULL
    OR RS.STATUS IS NULL OR TRIM(RS.STATUS) = '' OR SSM.STATUS_NAME IS NULL;

-- STEP 2 : CLEAN DATA TO STAGE
INSERT INTO ECOM_DEV_DB.STAGE.STAGE_SHIPMENTS
(
    SHIPMENT_ID,
    ORDER_ID,
    SHIP_DATE,
    DELIVERY_DATE,
    CARRIER,
    STATUS
)
SELECT
    TRY_CAST(TRIM(RS.SHIPMENT_ID) AS INT) AS SHIPMENT_ID,
    TRY_CAST(TRIM(RS.ORDER_ID) AS INT) AS ORDER_ID,
    TRY_TO_DATE(TRIM(RS.SHIP_DATE),'DD-MM-YYYY') AS SHIP_DATE,
    TRY_TO_DATE(TRIM(RS.DELIVERY_DATE),'DD-MM-YYYY') AS DELIVERY_DATE,
    SCM.CARRIER_NAME AS CARRIER,
    SSM.STATUS_NAME AS STATUS
FROM ECOM_DEV_DB.RAW.RAW_SHIPMENTS RS
INNER JOIN ECOM_DEV_DB.REFERENCE.SHIPMENT_CARRIER_MASTER SCM
    ON UPPER(TRIM(RS.CARRIER)) = UPPER(TRIM(SCM.CARRIER_NAME))
INNER JOIN ECOM_DEV_DB.REFERENCE.SHIPMENT_STATUS_MASTER SSM
    ON UPPER(TRIM(RS.STATUS)) = UPPER(TRIM(SSM.STATUS_NAME))
WHERE
    RS.SHIPMENT_ID IS NOT NULL AND TRIM(RS.SHIPMENT_ID) <> '' AND TRY_CAST(TRIM(RS.SHIPMENT_ID) AS INT) > 0
    AND RS.ORDER_ID IS NOT NULL AND TRIM(RS.ORDER_ID) <> '' AND TRY_CAST(TRIM(RS.ORDER_ID) AS INT) > 0
    AND RS.SHIP_DATE IS NOT NULL AND TRIM(RS.SHIP_DATE) <> '' AND TRY_TO_DATE(TRIM(RS.SHIP_DATE),'DD-MM-YYYY') IS NOT NULL AND TRY_TO_DATE(TRIM(RS.SHIP_DATE),'DD-MM-YYYY') <= CURRENT_DATE()
    AND RS.DELIVERY_DATE IS NOT NULL AND TRIM(RS.DELIVERY_DATE) <> '' AND TRY_TO_DATE(TRIM(RS.DELIVERY_DATE),'DD-MM-YYYY') IS NOT NULL AND TRY_TO_DATE(TRIM(RS.DELIVERY_DATE),'DD-MM-YYYY') <= CURRENT_DATE()
    AND TRY_TO_DATE(TRIM(RS.DELIVERY_DATE),'DD-MM-YYYY') >= TRY_TO_DATE(TRIM(RS.SHIP_DATE),'DD-MM-YYYY')
    AND RS.CARRIER IS NOT NULL;
    -- ============================================================================================================================
-- LOADING FROM RAW TO STAGE : EMPLOYEES
-- ============================================================================================================================

-- STEP 1 : REJECTED RECORDS TO DQ
INSERT INTO ECOM_DEV_DB.DQ.DQ_ERROR_LOG
(
    PIPELINE_NAME,
    LAYER_NAME,
    TABLE_NAME,
    BUSINESS_KEY,
    ERROR_TYPE,
    ERROR_MESSAGE,
    LOAD_TIMESTAMP,
    RAW_RECORD
)
SELECT
    'EMPLOYEE_PIPELINE',
    'RAW_TO_STAGE',
    'RAW_EMPLOYEES',
    TRY_CAST(TRIM(RE.EMPLOYEE_ID) AS INT),
    CASE
        WHEN RE.EMPLOYEE_ID IS NULL OR TRIM(RE.EMPLOYEE_ID) = '' THEN 'NULL_EMPLOYEE_ID'
        WHEN TRY_CAST(TRIM(RE.EMPLOYEE_ID) AS INT) <= 0 THEN 'INVALID_EMPLOYEE_ID'
        WHEN RE.NAME IS NULL OR TRIM(RE.NAME) = '' THEN 'NULL_NAME'
        WHEN RE.ROLE IS NULL OR TRIM(RE.ROLE) = '' THEN 'NULL_ROLE'
        WHEN ERM.ROLE_NAME IS NULL THEN 'INVALID_ROLE'
        WHEN RE.DEPARTMENT IS NULL OR TRIM(RE.DEPARTMENT) = '' THEN 'NULL_DEPARTMENT'
        WHEN DM.DEPT_NAME IS NULL THEN 'INVALID_DEPARTMENT'
        WHEN RE.COUNTRY IS NULL OR TRIM(RE.COUNTRY) = '' THEN 'NULL_COUNTRY'
        WHEN CM.COUNTRY_CODE IS NULL THEN 'INVALID_COUNTRY'
        WHEN RE.HIRED_DATE IS NULL OR TRIM(RE.HIRED_DATE) = '' THEN 'NULL_HIRED_DATE'
        WHEN TRY_TO_DATE(TRIM(RE.HIRED_DATE),'DD-MM-YYYY') IS NULL THEN 'INVALID_HIRED_DATE'
        WHEN TRY_TO_DATE(TRIM(RE.HIRED_DATE),'DD-MM-YYYY') > CURRENT_DATE() THEN 'FUTURE_HIRED_DATE'
    END AS ERROR_TYPE,
    CASE
        WHEN RE.EMPLOYEE_ID IS NULL OR TRIM(RE.EMPLOYEE_ID) = '' THEN 'EMPLOYEE ID IS NULL OR BLANK'
        WHEN TRY_CAST(TRIM(RE.EMPLOYEE_ID) AS INT) <= 0 THEN 'EMPLOYEE ID MUST BE GREATER THAN ZERO'
        WHEN RE.NAME IS NULL OR TRIM(RE.NAME) = '' THEN 'EMPLOYEE NAME IS NULL OR BLANK'
        WHEN RE.ROLE IS NULL OR TRIM(RE.ROLE) = '' THEN 'ROLE IS NULL OR BLANK'
        WHEN ERM.ROLE_NAME IS NULL THEN 'ROLE NOT FOUND IN EMPLOYEE_ROLE_MASTER'
        WHEN RE.DEPARTMENT IS NULL OR TRIM(RE.DEPARTMENT) = '' THEN 'DEPARTMENT IS NULL OR BLANK'
        WHEN DM.DEPT_NAME IS NULL THEN 'DEPARTMENT NOT FOUND IN DEPARTMENT_MASTER'
        WHEN RE.COUNTRY IS NULL OR TRIM(RE.COUNTRY) = '' THEN 'COUNTRY IS NULL OR BLANK'
        WHEN CM.COUNTRY_CODE IS NULL THEN 'COUNTRY NOT FOUND IN COUNTRY_MASTER'
        WHEN RE.HIRED_DATE IS NULL OR TRIM(RE.HIRED_DATE) = '' THEN 'HIRED DATE IS NULL OR BLANK'
        WHEN TRY_TO_DATE(TRIM(RE.HIRED_DATE),'DD-MM-YYYY') IS NULL THEN 'HIRED DATE FORMAT IS INVALID'
        WHEN TRY_TO_DATE(TRIM(RE.HIRED_DATE),'DD-MM-YYYY') > CURRENT_DATE() THEN 'HIRED DATE CANNOT BE IN FUTURE'
    END AS ERROR_MESSAGE,
    CURRENT_TIMESTAMP(),
    OBJECT_CONSTRUCT(*)
FROM ECOM_DEV_DB.RAW.RAW_EMPLOYEES RE
LEFT JOIN ECOM_DEV_DB.REFERENCE.EMPLOYEE_ROLE_MASTER ERM
    ON UPPER(TRIM(RE.ROLE)) = UPPER(TRIM(ERM.ROLE_NAME))
LEFT JOIN ECOM_DEV_DB.REFERENCE.DEPARTMENT_MASTER DM
    ON UPPER(TRIM(RE.DEPARTMENT)) = UPPER(TRIM(DM.DEPT_NAME))
LEFT JOIN ECOM_DEV_DB.REFERENCE.COUNTRY_MASTER CM
    ON UPPER(TRIM(RE.COUNTRY)) = UPPER(TRIM(CM.COUNTRY_NAME))
WHERE
    RE.EMPLOYEE_ID IS NULL OR TRIM(RE.EMPLOYEE_ID) = '' OR TRY_CAST(TRIM(RE.EMPLOYEE_ID) AS INT) <= 0
    OR RE.NAME IS NULL OR TRIM(RE.NAME) = ''
    OR RE.ROLE IS NULL OR TRIM(RE.ROLE) = '' OR ERM.ROLE_NAME IS NULL
    OR RE.DEPARTMENT IS NULL OR TRIM(RE.DEPARTMENT) = '' OR DM.DEPT_NAME IS NULL
    OR RE.COUNTRY IS NULL OR TRIM(RE.COUNTRY) = '' OR CM.COUNTRY_CODE IS NULL
    OR RE.HIRED_DATE IS NULL OR TRIM(RE.HIRED_DATE) = '' OR TRY_TO_DATE(TRIM(RE.HIRED_DATE),'DD-MM-YYYY') IS NULL OR TRY_TO_DATE(TRIM(RE.HIRED_DATE),'DD-MM-YYYY') > CURRENT_DATE();

-- STEP 2 : CLEAN DATA TO STAGE
INSERT INTO ECOM_DEV_DB.STAGE.STAGE_EMPLOYEES
(
    EMPLOYEE_ID,
    NAME,
    ROLE,
    DEPARTMENT,
    COUNTRY,
    HIRED_DATE
)
SELECT
    TRY_CAST(TRIM(RE.EMPLOYEE_ID) AS INT) AS EMPLOYEE_ID,
    UPPER(TRIM(RE.NAME)) AS NAME,
    ERM.ROLE_NAME AS ROLE,
    DM.DEPT_NAME AS DEPARTMENT,
    CM.COUNTRY_CODE AS COUNTRY,
    TRY_TO_DATE(TRIM(RE.HIRED_DATE),'DD-MM-YYYY') AS HIRED_DATE
FROM ECOM_DEV_DB.RAW.RAW_EMPLOYEES RE
INNER JOIN ECOM_DEV_DB.REFERENCE.EMPLOYEE_ROLE_MASTER ERM
    ON UPPER(TRIM(RE.ROLE)) = UPPER(TRIM(ERM.ROLE_NAME))
INNER JOIN ECOM_DEV_DB.REFERENCE.DEPARTMENT_MASTER DM
    ON UPPER(TRIM(RE.DEPARTMENT)) = UPPER(TRIM(DM.DEPT_NAME))
INNER JOIN ECOM_DEV_DB.REFERENCE.COUNTRY_MASTER CM
    ON UPPER(TRIM(RE.COUNTRY)) = UPPER(TRIM(CM.COUNTRY_NAME))
WHERE
    RE.EMPLOYEE_ID IS NOT NULL AND TRIM(RE.EMPLOYEE_ID) <> '' AND TRY_CAST(TRIM(RE.EMPLOYEE_ID) AS INT) > 0
    AND RE.NAME IS NOT NULL AND TRIM(RE.NAME) <> ''
    AND RE.ROLE IS NOT NULL AND TRIM(RE.ROLE) <> ''
    AND RE.DEPARTMENT IS NOT NULL AND TRIM(RE.DEPARTMENT) <> ''
    AND RE.COUNTRY IS NOT NULL AND TRIM(RE.COUNTRY) <> ''
    AND RE.HIRED_DATE IS NOT NULL AND TRIM(RE.HIRED_DATE) <> ''
    AND TRY_TO_DATE(TRIM(RE.HIRED_DATE),'DD-MM-YYYY') IS NOT NULL
    AND TRY_TO_DATE(TRIM(RE.HIRED_DATE),'DD-MM-YYYY') <= CURRENT_DATE();
    -- ============================================================================================================================
-- LOADING FROM RAW TO STAGE : PRODUCTS
-- ============================================================================================================================

-- STEP 1 : REJECTED RECORDS TO DQ
INSERT INTO ECOM_DEV_DB.DQ.DQ_ERROR_LOG
(
    PIPELINE_NAME,
    LAYER_NAME,
    TABLE_NAME,
    BUSINESS_KEY,
    ERROR_TYPE,
    ERROR_MESSAGE,
    LOAD_TIMESTAMP,
    RAW_RECORD
)
SELECT
    'PRODUCT_PIPELINE',
    'RAW_TO_STAGE',
    'RAW_PRODUCTS',
    TRY_CAST(TRIM(RP.PRODUCT_ID) AS INT),
    CASE
        WHEN RP.PRODUCT_ID IS NULL OR TRIM(RP.PRODUCT_ID) = '' THEN 'NULL_PRODUCT_ID'
        WHEN TRY_CAST(TRIM(RP.PRODUCT_ID) AS INT) <= 0 THEN 'INVALID_PRODUCT_ID'
        WHEN RP.NAME IS NULL OR TRIM(RP.NAME) = '' THEN 'NULL_PRODUCT_NAME'
        WHEN RP.CATEGORY IS NULL OR TRIM(RP.CATEGORY) = '' THEN 'NULL_CATEGORY'
        WHEN PCM.CATEGORY_NAME IS NULL THEN 'INVALID_CATEGORY'
        WHEN RP.PRICE IS NULL OR TRIM(RP.PRICE) = '' THEN 'NULL_PRICE'
        WHEN TRY_CAST(TRIM(RP.PRICE) AS DECIMAL(18,2)) IS NULL THEN 'INVALID_PRICE'
        WHEN TRY_CAST(TRIM(RP.PRICE) AS DECIMAL(18,2)) < 0 THEN 'NEGATIVE_PRICE'
        WHEN RP.CURRENCY IS NULL OR TRIM(RP.CURRENCY) = '' THEN 'NULL_CURRENCY'
        WHEN CM.CURRENCY_CODE IS NULL THEN 'INVALID_CURRENCY'
        WHEN RP.STOCK_QUANTITY IS NULL OR TRIM(RP.STOCK_QUANTITY) = '' THEN 'NULL_STOCK_QUANTITY'
        WHEN TRY_CAST(TRIM(RP.STOCK_QUANTITY) AS INT) IS NULL THEN 'INVALID_STOCK_QUANTITY'
        WHEN TRY_CAST(TRIM(RP.STOCK_QUANTITY) AS INT) < 0 THEN 'NEGATIVE_STOCK_QUANTITY'
        WHEN RP.SUPPLIER_ID IS NULL OR TRIM(RP.SUPPLIER_ID) = '' THEN 'NULL_SUPPLIER'
        WHEN SM.SUPPLIER_ID IS NULL THEN 'INVALID_SUPPLIER'
    END AS ERROR_TYPE,
    CASE
        WHEN RP.PRODUCT_ID IS NULL OR TRIM(RP.PRODUCT_ID) = '' THEN 'PRODUCT ID IS NULL OR BLANK'
        WHEN TRY_CAST(TRIM(RP.PRODUCT_ID) AS INT) <= 0 THEN 'PRODUCT ID MUST BE GREATER THAN ZERO'
        WHEN RP.NAME IS NULL OR TRIM(RP.NAME) = '' THEN 'PRODUCT NAME IS NULL OR BLANK'
        WHEN RP.CATEGORY IS NULL OR TRIM(RP.CATEGORY) = '' THEN 'CATEGORY IS NULL OR BLANK'
        WHEN PCM.CATEGORY_NAME IS NULL THEN 'CATEGORY NOT FOUND IN PRODUCT_CATEGORY_MASTER'
        WHEN RP.PRICE IS NULL OR TRIM(RP.PRICE) = '' THEN 'PRICE IS NULL OR BLANK'
        WHEN TRY_CAST(TRIM(RP.PRICE) AS DECIMAL(18,2)) IS NULL THEN 'PRICE IS NOT NUMERIC'
        WHEN TRY_CAST(TRIM(RP.PRICE) AS DECIMAL(18,2)) < 0 THEN 'PRICE CANNOT BE NEGATIVE'
        WHEN RP.CURRENCY IS NULL OR TRIM(RP.CURRENCY) = '' THEN 'CURRENCY IS NULL OR BLANK'
        WHEN CM.CURRENCY_CODE IS NULL THEN 'CURRENCY NOT FOUND IN CURRENCY_MASTER'
        WHEN RP.STOCK_QUANTITY IS NULL OR TRIM(RP.STOCK_QUANTITY) = '' THEN 'STOCK QUANTITY IS NULL OR BLANK'
        WHEN TRY_CAST(TRIM(RP.STOCK_QUANTITY) AS INT) IS NULL THEN 'STOCK QUANTITY IS NOT NUMERIC'
        WHEN TRY_CAST(TRIM(RP.STOCK_QUANTITY) AS INT) < 0 THEN 'STOCK QUANTITY CANNOT BE NEGATIVE'
        WHEN RP.SUPPLIER_ID IS NULL OR TRIM(RP.SUPPLIER_ID) = '' THEN 'SUPPLIER IS NULL OR BLANK'
        WHEN SM.SUPPLIER_ID IS NULL THEN 'SUPPLIER NOT FOUND IN SUPPLIER_MASTER'
    END AS ERROR_MESSAGE,
    CURRENT_TIMESTAMP(),
    OBJECT_CONSTRUCT(*)
FROM ECOM_DEV_DB.RAW.RAW_PRODUCTS RP
LEFT JOIN ECOM_DEV_DB.REFERENCE.PRODUCT_CATEGORY_MASTER PCM
    ON UPPER(TRIM(RP.CATEGORY)) = UPPER(TRIM(PCM.CATEGORY_NAME))
LEFT JOIN ECOM_DEV_DB.REFERENCE.CURRENCY_MASTER CM
    ON UPPER(TRIM(RP.CURRENCY)) = UPPER(TRIM(CM.CURRENCY_CODE))
LEFT JOIN ECOM_DEV_DB.REFERENCE.SUPPLIER_MASTER SM
    ON TRY_CAST(TRIM(RP.SUPPLIER_ID) AS INT) = SM.SUPPLIER_ID
WHERE
    RP.PRODUCT_ID IS NULL OR TRIM(RP.PRODUCT_ID) = '' OR TRY_CAST(TRIM(RP.PRODUCT_ID) AS INT) <= 0
    OR RP.NAME IS NULL OR TRIM(RP.NAME) = ''
    OR RP.CATEGORY IS NULL OR TRIM(RP.CATEGORY) = '' OR PCM.CATEGORY_NAME IS NULL
    OR RP.PRICE IS NULL OR TRIM(RP.PRICE) = '' OR TRY_CAST(TRIM(RP.PRICE) AS DECIMAL(18,2)) IS NULL OR TRY_CAST(TRIM(RP.PRICE) AS DECIMAL(18,2)) < 0
    OR RP.CURRENCY IS NULL OR TRIM(RP.CURRENCY) = '' OR CM.CURRENCY_CODE IS NULL
    OR RP.STOCK_QUANTITY IS NULL OR TRIM(RP.STOCK_QUANTITY) = '' OR TRY_CAST(TRIM(RP.STOCK_QUANTITY) AS INT) IS NULL OR TRY_CAST(TRIM(RP.STOCK_QUANTITY) AS INT) < 0
    OR RP.SUPPLIER_ID IS NULL OR TRIM(RP.SUPPLIER_ID) = '' OR SM.SUPPLIER_ID IS NULL;

-- STEP 2 : CLEAN DATA TO STAGE
INSERT INTO ECOM_DEV_DB.STAGE.STAGE_PRODUCTS
(
    PRODUCT_ID,
    NAME,
    CATEGORY,
    PRICE,
    CURRENCY,
    STOCK_QUANTITY,
    SUPPLIER_ID
)
SELECT
    TRY_CAST(TRIM(RP.PRODUCT_ID) AS INT) AS PRODUCT_ID,
    UPPER(TRIM(RP.NAME)) AS NAME,
    PCM.CATEGORY_NAME AS CATEGORY,
    TRY_CAST(TRIM(RP.PRICE) AS DECIMAL(18,2)) AS PRICE,
    CM.CURRENCY_CODE AS CURRENCY,
    TRY_CAST(TRIM(RP.STOCK_QUANTITY) AS INT) AS STOCK_QUANTITY,
    SM.SUPPLIER_ID AS SUPPLIER_ID
FROM ECOM_DEV_DB.RAW.RAW_PRODUCTS RP
INNER JOIN ECOM_DEV_DB.REFERENCE.PRODUCT_CATEGORY_MASTER PCM
    ON UPPER(TRIM(RP.CATEGORY)) = UPPER(TRIM(PCM.CATEGORY_NAME))
INNER JOIN ECOM_DEV_DB.REFERENCE.CURRENCY_MASTER CM
    ON UPPER(TRIM(RP.CURRENCY)) = UPPER(TRIM(CM.CURRENCY_CODE))
INNER JOIN ECOM_DEV_DB.REFERENCE.SUPPLIER_MASTER SM
    ON TRY_CAST(TRIM(RP.SUPPLIER_ID) AS INT) = SM.SUPPLIER_ID
WHERE
    RP.PRODUCT_ID IS NOT NULL AND TRIM(RP.PRODUCT_ID) <> '' AND TRY_CAST(TRIM(RP.PRODUCT_ID) AS INT) > 0
    AND RP.NAME IS NOT NULL AND TRIM(RP.NAME) <> ''
    AND RP.CATEGORY IS NOT NULL AND TRIM(RP.CATEGORY) <> ''
    AND RP.PRICE IS NOT NULL AND TRIM(RP.PRICE) <> '' AND TRY_CAST(TRIM(RP.PRICE) AS DECIMAL(18,2)) >= 0
    AND RP.CURRENCY IS NOT NULL AND TRIM(RP.CURRENCY) <> ''
    AND RP.STOCK_QUANTITY IS NOT NULL AND TRIM(RP.STOCK_QUANTITY) <> '' AND TRY_CAST(TRIM(RP.STOCK_QUANTITY) AS INT) >= 0
    AND RP.SUPPLIER_ID IS NOT NULL AND TRIM(RP.SUPPLIER_ID) <> '';