-- test 3 from clean to gold ###################################################################################################

    CREATE OR REPLACE VIEW ECOM_DEV_DB.TEST.VW_CLEAN_CUSTOMERS_VALIDATION AS
SELECT
    C.*,
    CASE WHEN CUSTOMER_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS CUSTOMER_ID_CHECK,
    CASE WHEN EMAIL IS NULL OR NOT REGEXP_LIKE(EMAIL,'^[^@]+@[^@]+\.[^@]+$') THEN 'FAIL' ELSE 'PASS' END AS EMAIL_CHECK,
    CASE WHEN CREATED_AT IS NULL OR CREATED_AT > CURRENT_DATE() THEN 'FAIL' ELSE 'PASS' END AS CREATED_AT_CHECK
FROM ECOM_DEV_DB.CLEAN.CUSTOMERS_CLEAN C;

CREATE OR REPLACE VIEW ECOM_DEV_DB.TEST.VW_CLEAN_PRODUCTS_VALIDATION AS
SELECT
    P.*,
    CASE WHEN PRODUCT_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS PRODUCT_ID_CHECK,
    CASE WHEN PRICE IS NULL OR PRICE < 0 THEN 'FAIL' ELSE 'PASS' END AS PRICE_CHECK,
    CASE WHEN STOCK_QUANTITY IS NULL OR STOCK_QUANTITY < 0 THEN 'FAIL' ELSE 'PASS' END AS STOCK_CHECK,
    CASE WHEN CURRENCY IS NULL OR TRIM(CURRENCY) = '' THEN 'FAIL' ELSE 'PASS' END AS CURRENCY_CHECK
FROM ECOM_DEV_DB.CLEAN.PRODUCTS_CLEAN P;

CREATE OR REPLACE VIEW ECOM_DEV_DB.TEST.VW_CLEAN_EMPLOYEES_VALIDATION AS
SELECT
    E.*,
    CASE WHEN EMPLOYEE_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS EMPLOYEE_ID_CHECK,
    CASE WHEN NAME IS NULL OR TRIM(NAME) = '' THEN 'FAIL' ELSE 'PASS' END AS NAME_CHECK,
    CASE WHEN HIRED_DATE IS NULL OR HIRED_DATE > CURRENT_DATE() THEN 'FAIL' ELSE 'PASS' END AS HIRED_DATE_CHECK,
    CASE WHEN ROLE IS NULL OR TRIM(ROLE) = '' THEN 'FAIL' ELSE 'PASS' END AS ROLE_CHECK
FROM ECOM_DEV_DB.CLEAN.EMPLOYEES_CLEAN E;

CREATE OR REPLACE VIEW ECOM_DEV_DB.TEST.VW_CLEAN_ORDERS_VALIDATION AS
SELECT
    O.*,
    CASE WHEN ORDER_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS ORDER_ID_CHECK,
    CASE WHEN CUSTOMER_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS CUSTOMER_ID_CHECK,
    CASE WHEN TOTAL_AMOUNT IS NULL OR TOTAL_AMOUNT < 0 THEN 'FAIL' ELSE 'PASS' END AS TOTAL_AMOUNT_CHECK,
    CASE WHEN ORDER_DATE IS NULL OR ORDER_DATE > CURRENT_DATE() THEN 'FAIL' ELSE 'PASS' END AS ORDER_DATE_CHECK,
    CASE WHEN C.CUSTOMER_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS CUSTOMER_EXISTS_CHECK
FROM ECOM_DEV_DB.CLEAN.ORDERS_CLEAN O
LEFT JOIN ECOM_DEV_DB.CLEAN.CUSTOMERS_CLEAN C
    ON O.CUSTOMER_ID = C.CUSTOMER_ID;

    CREATE OR REPLACE VIEW ECOM_DEV_DB.TEST.VW_CLEAN_PAYMENTS_VALIDATION AS
SELECT
    P.*,
    CASE WHEN PAYMENT_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS PAYMENT_ID_CHECK,
    CASE WHEN ORDER_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS ORDER_ID_CHECK,
    CASE WHEN AMOUNT IS NULL OR AMOUNT < 0 THEN 'FAIL' ELSE 'PASS' END AS AMOUNT_CHECK,
    CASE WHEN PAYMENT_DATE IS NULL OR PAYMENT_DATE > CURRENT_DATE() THEN 'FAIL' ELSE 'PASS' END AS PAYMENT_DATE_CHECK,
    CASE WHEN O.ORDER_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS ORDER_EXISTS_CHECK
FROM ECOM_DEV_DB.CLEAN.PAYMENTS_CLEAN P
LEFT JOIN ECOM_DEV_DB.CLEAN.ORDERS_CLEAN O
    ON P.ORDER_ID = O.ORDER_ID;

    CREATE OR REPLACE VIEW ECOM_DEV_DB.TEST.VW_CLEAN_SHIPMENTS_VALIDATION AS
SELECT
    S.*,
    CASE WHEN SHIPMENT_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS SHIPMENT_ID_CHECK,
    CASE WHEN ORDER_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS ORDER_ID_CHECK,
    CASE WHEN SHIP_DATE IS NULL OR SHIP_DATE > CURRENT_DATE() THEN 'FAIL' ELSE 'PASS' END AS SHIP_DATE_CHECK,
    CASE WHEN DELIVERY_DATE IS NULL OR DELIVERY_DATE < SHIP_DATE THEN 'FAIL' ELSE 'PASS' END AS DELIVERY_DATE_CHECK,
    CASE WHEN O.ORDER_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS ORDER_EXISTS_CHECK
FROM ECOM_DEV_DB.CLEAN.SHIPMENTS_CLEAN S
LEFT JOIN ECOM_DEV_DB.CLEAN.ORDERS_CLEAN O
    ON S.ORDER_ID = O.ORDER_ID;