-- Orders & Fulfillment
-- ============================================================
-- VIEW NAME: VW_ORDER_CANCELLATION_ANALYTICS
-- PURPOSE: Track cancelled orders and revenue impact
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_ORDER_CANCELLATION_ANALYTICS AS
SELECT
    O.ORDER_ID,
    O.CUSTOMER_ID,
    O.ORDER_DATE,
    O.STATUS,
    O.TOTAL_AMOUNT
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
WHERE UPPER(O.STATUS) = 'CANCELLED'
ORDER BY O.ORDER_DATE DESC;

-- ============================================================
-- VIEW NAME: VW_LATE_DELIVERIES_ANALYTICS
-- PURPOSE: Identify shipments delivered after expected date
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_LATE_DELIVERIES_ANALYTICS AS
SELECT
    S.SHIPMENT_ID,
    S.ORDER_ID,
    S.CARRIER,
    S.SHIP_DATE,
    S.DELIVERY_DATE,
    (S.DELIVERY_DATE - S.SHIP_DATE) AS DELIVERY_DAYS
FROM ECOM_DEV_DB.GOLD.FACT_SHIPMENTS S
WHERE S.DELIVERY_DATE > S.SHIP_DATE + INTERVAL '5' DAY
ORDER BY DELIVERY_DAYS DESC;

-- ============================================================
-- VIEW NAME: VW_DELIVERY_TIME_BY_CARRIER_ANALYTICS
-- PURPOSE: Average delivery time per carrier
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_DELIVERY_TIME_BY_CARRIER_ANALYTICS AS
SELECT
    S.CARRIER,
    ROUND(AVG(S.DELIVERY_DATE - S.SHIP_DATE), 2) AS AVG_DELIVERY_DAYS,
    COUNT(DISTINCT S.SHIPMENT_ID) AS TOTAL_SHIPMENTS
FROM ECOM_DEV_DB.GOLD.FACT_SHIPMENTS S
GROUP BY S.CARRIER
ORDER BY AVG_DELIVERY_DAYS;

-- ============================================================
-- VIEW NAME: VW_ORDERS_BY_PAYMENT_METHOD_ANALYTICS
-- PURPOSE: Analyze orders by payment method
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_ORDERS_BY_PAYMENT_METHOD_ANALYTICS AS
SELECT
    P.PAYMENT_METHOD,
    COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS,
    SUM(P.AMOUNT) AS TOTAL_REVENUE
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.FACT_PAYMENTS P ON O.ORDER_ID = P.ORDER_ID
GROUP BY P.PAYMENT_METHOD
ORDER BY TOTAL_REVENUE DESC;

-- ============================================================
-- VIEW NAME: VW_ORDERS_BY_CATEGORY_ANALYTICS
-- PURPOSE: Revenue and order count by product category
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_ORDERS_BY_CATEGORY_ANALYTICS AS
SELECT
    P.CATEGORY,
    COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS,
    SUM(O.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.DIM_PRODUCTS P ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

-- ============================================================
-- VIEW NAME: VW_ORDERS_BY_COUNTRY_MONTHLY_ANALYTICS
-- PURPOSE: Monthly orders and revenue by country
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_ORDERS_BY_COUNTRY_MONTHLY_ANALYTICS AS
SELECT
    C.COUNTRY,
    TO_CHAR(O.ORDER_DATE, 'YYYY-MM') AS MONTH,
    COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS,
    SUM(P.AMOUNT) AS TOTAL_REVENUE
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.FACT_PAYMENTS P ON O.ORDER_ID = P.ORDER_ID
JOIN ECOM_DEV_DB.GOLD.DIM_CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.COUNTRY, TO_CHAR(O.ORDER_DATE, 'YYYY-MM')
ORDER BY C.COUNTRY, MONTH;

-- ============================================================
-- VIEW NAME: VW_BASKET_ANALYSIS_ANALYTICS
-- PURPOSE: Analyze average basket size and value per order
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_BASKET_ANALYSIS_ANALYTICS AS
SELECT
    O.ORDER_ID,
    COUNT(DISTINCT O.PRODUCT_ID) AS PRODUCTS_PER_ORDER,
    SUM(O.TOTAL_AMOUNT) AS ORDER_VALUE
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
GROUP BY O.ORDER_ID
ORDER BY ORDER_VALUE DESC;

-- ============================================================
-- VIEW NAME: VW_RETURN_RATE_BY_CATEGORY_ANALYTICS
-- PURPOSE: Calculate return rate by product category
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_RETURN_RATE_BY_CATEGORY_ANALYTICS AS
SELECT
    P.CATEGORY,
    COUNT(DISTINCT R.RETURN_ID) AS TOTAL_RETURNS,
    COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS,
    ROUND(COUNT(DISTINCT R.RETURN_ID) / NULLIF(COUNT(DISTINCT O.ORDER_ID),0) * 100, 2) AS RETURN_RATE_PERCENT
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.DIM_PRODUCTS P ON O.PRODUCT_ID = P.PRODUCT_ID
LEFT JOIN ECOM_DEV_DB.GOLD.FACT_RETURNS R ON O.ORDER_ID = R.ORDER_ID
GROUP BY P.CATEGORY
ORDER BY RETURN_RATE_PERCENT DESC;

-- ============================================================
-- VIEW NAME: VW_PAYMENT_MISMATCH_ANALYTICS
-- PURPOSE: Detect mismatches between order total and payment amount
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_PAYMENT_MISMATCH_ANALYTICS AS
SELECT
    O.ORDER_ID,
    O.TOTAL_AMOUNT AS ORDER_TOTAL,
    SUM(P.AMOUNT) AS PAYMENT_TOTAL,
    (SUM(P.AMOUNT) - O.TOTAL_AMOUNT) AS DIFFERENCE
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.FACT_PAYMENTS P ON O.ORDER_ID = P.ORDER_ID
GROUP BY O.ORDER_ID, O.TOTAL_AMOUNT
HAVING SUM(P.AMOUNT) <> O.TOTAL_AMOUNT
ORDER BY DIFFERENCE DESC;

-- ============================================================
-- VIEW NAME: VW_ORDER_OUTLIERS_ANALYTICS
-- PURPOSE: Identify unusually high or low order values
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_ORDER_OUTLIERS_ANALYTICS AS
SELECT
    O.ORDER_ID,
    O.CUSTOMER_ID,
    O.ORDER_DATE,
    O.TOTAL_AMOUNT
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
WHERE O.TOTAL_AMOUNT > 10000   -- High-value outlier
   OR O.TOTAL_AMOUNT < 10      -- Low-value outlier
ORDER BY O.TOTAL_AMOUNT DESC;

-- ============================================================
-- VIEW NAME: VW_DELIVERY_SLA_COMPLIANCE_ANALYTICS
-- PURPOSE: Measure compliance with delivery SLA (e.g., 5 days)
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_DELIVERY_SLA_COMPLIANCE_ANALYTICS AS
SELECT
    S.CARRIER,
    COUNT(DISTINCT S.SHIPMENT_ID) AS TOTAL_SHIPMENTS,
    COUNT(DISTINCT CASE WHEN S.DELIVERY_DATE <= S.SHIP_DATE + INTERVAL '5' DAY THEN S.SHIPMENT_ID END) AS SLA_COMPLIANT,
    ROUND(
        COUNT(DISTINCT CASE WHEN S.DELIVERY_DATE <= S.SHIP_DATE + INTERVAL '5' DAY THEN S.SHIPMENT_ID END)
        / NULLIF(COUNT(DISTINCT S.SHIPMENT_ID),0) * 100, 2
    ) AS SLA_COMPLIANCE_PERCENT
FROM ECOM_DEV_DB.GOLD.FACT_SHIPMENTS S
GROUP BY S.CARRIER
ORDER BY SLA_COMPLIANCE_PERCENT DESC;

-- ============================================================
-- VIEW NAME: VW_RETURN_REASON_ANALYTICS
-- PURPOSE: Analyze reasons for product returns
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_RETURN_REASON_ANALYTICS AS
SELECT
    R.RETURN_REASON,
    COUNT(DISTINCT R.RETURN_ID) AS TOTAL_RETURNS,
    SUM(R.REFUND_AMOUNT) AS TOTAL_REFUND_VALUE
FROM ECOM_DEV_DB.GOLD.FACT_RETURNS R
GROUP BY R.RETURN_REASON
ORDER BY TOTAL_RETURNS DESC;