-- Inventory & Suppliers
-- ============================================================
-- VIEW NAME: VW_OUT_OF_STOCK_PRODUCTS_ANALYTICS
-- PURPOSE: Identify products currently out of stock
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_OUT_OF_STOCK_PRODUCTS_ANALYTICS AS
SELECT
    P.PRODUCT_ID,
    P.NAME AS PRODUCT_NAME,
    P.CATEGORY,
    P.STOCK_QUANTITY
FROM ECOM_DEV_DB.GOLD.DIM_PRODUCTS P
WHERE P.STOCK_QUANTITY = 0
ORDER BY P.CATEGORY, P.NAME;

-- ============================================================
-- VIEW NAME: VW_HIGH_MARGIN_PRODUCTS_ANALYTICS
-- PURPOSE: List products with high profit margins
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_HIGH_MARGIN_PRODUCTS_ANALYTICS AS
SELECT
    P.PRODUCT_ID,
    P.NAME AS PRODUCT_NAME,
    P.CATEGORY,
    P.PRICE,
    P.COST,
    ROUND(((P.PRICE - P.COST) / NULLIF(P.PRICE,0)) * 100, 2) AS MARGIN_PERCENT
FROM ECOM_DEV_DB.GOLD.DIM_PRODUCTS P
WHERE (P.PRICE - P.COST) > 0
ORDER BY MARGIN_PERCENT DESC;

-- ============================================================
-- VIEW NAME: VW_STOCK_TURNOVER_ANALYTICS
-- PURPOSE: Measure stock turnover rate by product
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_STOCK_TURNOVER_ANALYTICS AS
SELECT
    P.PRODUCT_ID,
    P.NAME AS PRODUCT_NAME,
    SUM(O.QUANTITY) AS UNITS_SOLD,
    P.STOCK_QUANTITY,
    ROUND(SUM(O.QUANTITY) / NULLIF(P.STOCK_QUANTITY,0), 2) AS STOCK_TURNOVER_RATIO
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.DIM_PRODUCTS P ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.NAME, P.STOCK_QUANTITY
ORDER BY STOCK_TURNOVER_RATIO DESC;

-- ============================================================
-- VIEW NAME: VW_SUPPLIER_PERFORMANCE_ANALYTICS
-- PURPOSE: Evaluate supplier performance based on delivery timeliness
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_SUPPLIER_PERFORMANCE_ANALYTICS AS
SELECT
    S.SUPPLIER_ID,
    S.NAME AS SUPPLIER_NAME,
    COUNT(DISTINCT SH.SHIPMENT_ID) AS TOTAL_SHIPMENTS,
    ROUND(AVG(SH.DELIVERY_DATE - SH.SHIP_DATE), 2) AS AVG_DELIVERY_DAYS
FROM ECOM_DEV_DB.GOLD.DIM_SUPPLIERS S
JOIN ECOM_DEV_DB.GOLD.FACT_SHIPMENTS SH ON S.SUPPLIER_ID = SH.SUPPLIER_ID
GROUP BY S.SUPPLIER_ID, S.NAME
ORDER BY AVG_DELIVERY_DAYS;

-- ============================================================
-- VIEW NAME: VW_PRODUCT_POPULARITY_ANALYTICS
-- PURPOSE: Rank products by number of orders
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_PRODUCT_POPULARITY_ANALYTICS AS
SELECT
    P.PRODUCT_ID,
    P.NAME AS PRODUCT_NAME,
    COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.DIM_PRODUCTS P ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.NAME
ORDER BY TOTAL_ORDERS DESC;

-- ============================================================
-- VIEW NAME: VW_DECLINING_PRODUCTS_ANALYTICS
-- PURPOSE: Identify products with declining sales month-over-month
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_DECLINING_PRODUCTS_ANALYTICS AS
SELECT
    P.PRODUCT_ID,
    P.NAME AS PRODUCT_NAME,
    TO_CHAR(O.ORDER_DATE, 'YYYY-MM') AS MONTH,
    SUM(O.QUANTITY) AS UNITS_SOLD,
    LAG(SUM(O.QUANTITY)) OVER (PARTITION BY P.PRODUCT_ID ORDER BY TO_CHAR(O.ORDER_DATE,'YYYY-MM')) AS PREV_MONTH_UNITS,
    CASE 
        WHEN SUM(O.QUANTITY) < LAG(SUM(O.QUANTITY)) OVER (PARTITION BY P.PRODUCT_ID ORDER BY TO_CHAR(O.ORDER_DATE,'YYYY-MM'))
        THEN 'Declining'
        ELSE 'Stable/Increasing'
    END AS SALES_TREND
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.DIM_PRODUCTS P ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.NAME, TO_CHAR(O.ORDER_DATE,'YYYY-MM')
ORDER BY P.PRODUCT_ID, MONTH;

-- ============================================================
-- VIEW NAME: VW_HIGH_RETURN_PRODUCTS_ANALYTICS
-- PURPOSE: Identify products with high return rates
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_HIGH_RETURN_PRODUCTS_ANALYTICS AS
SELECT
    P.PRODUCT_ID,
    P.NAME AS PRODUCT_NAME,
    COUNT(DISTINCT R.RETURN_ID) AS TOTAL_RETURNS,
    COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS,
    ROUND(COUNT(DISTINCT R.RETURN_ID) / NULLIF(COUNT(DISTINCT O.ORDER_ID),0) * 100, 2) AS RETURN_RATE_PERCENT
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.DIM_PRODUCTS P ON O.PRODUCT_ID = P.PRODUCT_ID
LEFT JOIN ECOM_DEV_DB.GOLD.FACT_RETURNS R ON O.ORDER_ID = R.ORDER_ID
GROUP BY P.PRODUCT_ID, P.NAME
ORDER BY RETURN_RATE_PERCENT DESC;

-- ============================================================
-- VIEW NAME: VW_INVENTORY_AGING_ANALYTICS
-- PURPOSE: Track aging inventory based on last restock date
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_INVENTORY_AGING_ANALYTICS AS
SELECT
    P.PRODUCT_ID,
    P.NAME AS PRODUCT_NAME,
    P.CATEGORY,
    P.STOCK_QUANTITY,
    P.LAST_RESTOCK_DATE,
    (CURRENT_DATE - P.LAST_RESTOCK_DATE) AS DAYS_IN_STOCK
FROM ECOM_DEV_DB.GOLD.DIM_PRODUCTS P
WHERE P.STOCK_QUANTITY > 0
ORDER BY DAYS_IN_STOCK DESC;

-- ============================================================
-- VIEW NAME: VW_TOP_SUPPLIERS_ANALYTICS
-- PURPOSE: Rank suppliers by total supplied products
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_TOP_SUPPLIERS_ANALYTICS AS
SELECT
    S.SUPPLIER_ID,
    S.NAME AS SUPPLIER_NAME,
    COUNT(DISTINCT P.PRODUCT_ID) AS TOTAL_PRODUCTS_SUPPLIED
FROM ECOM_DEV_DB.GOLD.DIM_SUPPLIERS S
JOIN ECOM_DEV_DB.GOLD.DIM_PRODUCTS P ON S.SUPPLIER_ID = P.SUPPLIER_ID
GROUP BY S.SUPPLIER_ID, S.NAME
ORDER BY TOTAL_PRODUCTS_SUPPLIED DESC;

-- ============================================================
-- VIEW NAME: VW_PRODUCT_LIFECYCLE_ANALYTICS
-- PURPOSE: Track product lifecycle stages based on sales activity
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_PRODUCT_LIFECYCLE_ANALYTICS AS
SELECT
    P.PRODUCT_ID,
    P.NAME AS PRODUCT_NAME,
    CASE 
        WHEN SUM(O.QUANTITY) = 0 THEN 'Inactive'
        WHEN SUM(O.QUANTITY) < 100 THEN 'Introduction'
        WHEN SUM(O.QUANTITY) BETWEEN 100 AND 1000 THEN 'Growth'
        WHEN SUM(O.QUANTITY) BETWEEN 1001 AND 5000 THEN 'Maturity'
        ELSE 'Decline'
    END AS LIFECYCLE_STAGE,
    SUM(O.QUANTITY) AS TOTAL_UNITS_SOLD
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.DIM_PRODUCTS P ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.NAME
ORDER BY TOTAL_UNITS_SOLD DESC;