-- customer views 
-- ============================================================
-- VIEW NAME: VW_TOP_CUSTOMERS_ANALYTICS
-- PURPOSE: Identify top customers by total spend
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_TOP_CUSTOMERS_ANALYTICS AS
SELECT
    C.CUSTOMER_ID,
    C.NAME AS CUSTOMER_NAME,
    SUM(P.AMOUNT) AS TOTAL_SPEND,
    COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.FACT_PAYMENTS P ON O.ORDER_ID = P.ORDER_ID
JOIN ECOM_DEV_DB.GOLD.DIM_CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.NAME
ORDER BY TOTAL_SPEND DESC
LIMIT 10;

-- ============================================================
-- VIEW NAME: VW_NEW_CUSTOMERS_MONTHLY_ANALYTICS
-- PURPOSE: Track new customer registrations per month
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_NEW_CUSTOMERS_MONTHLY_ANALYTICS AS
SELECT
    TO_CHAR(C.CREATED_AT, 'YYYY-MM') AS MONTH,
    COUNT(DISTINCT C.CUSTOMER_ID) AS NEW_CUSTOMERS
FROM ECOM_DEV_DB.GOLD.DIM_CUSTOMERS C
GROUP BY TO_CHAR(C.CREATED_AT, 'YYYY-MM')
ORDER BY MONTH;

-- ============================================================
-- VIEW NAME: VW_REPEAT_PURCHASE_RATE_ANALYTICS
-- PURPOSE: Calculate repeat purchase rate
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_REPEAT_PURCHASE_RATE_ANALYTICS AS
SELECT
    ROUND(
        COUNT(DISTINCT CASE WHEN ORDER_COUNT > 1 THEN CUSTOMER_ID END) 
        / NULLIF(COUNT(DISTINCT CUSTOMER_ID),0) * 100, 2
    ) AS REPEAT_PURCHASE_RATE_PERCENT
FROM (
    SELECT CUSTOMER_ID, COUNT(DISTINCT ORDER_ID) AS ORDER_COUNT
    FROM ECOM_DEV_DB.GOLD.FACT_ORDERS
    GROUP BY CUSTOMER_ID
) T;

-- ============================================================
-- VIEW NAME: VW_CUSTOMER_CHURN_ANALYTICS
-- PURPOSE: Identify customers who have not ordered in last 6 months
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_CUSTOMER_CHURN_ANALYTICS AS
SELECT
    C.CUSTOMER_ID,
    C.NAME AS CUSTOMER_NAME,
    MAX(O.ORDER_DATE) AS LAST_ORDER_DATE
FROM ECOM_DEV_DB.GOLD.DIM_CUSTOMERS C
LEFT JOIN ECOM_DEV_DB.GOLD.FACT_ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.NAME
HAVING MAX(O.ORDER_DATE) < ADD_MONTHS(CURRENT_DATE, -6);

-- ============================================================
-- VIEW NAME: VW_CUSTOMER_SEGMENTATION_ANALYTICS
-- PURPOSE: Segment customers by spend level
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_CUSTOMER_SEGMENTATION_ANALYTICS AS
SELECT
    C.CUSTOMER_ID,
    C.NAME AS CUSTOMER_NAME,
    SUM(P.AMOUNT) AS TOTAL_SPEND,
    CASE 
        WHEN SUM(P.AMOUNT) >= 10000 THEN 'High Value'
        WHEN SUM(P.AMOUNT) BETWEEN 5000 AND 9999 THEN 'Medium Value'
        ELSE 'Low Value'
    END AS SEGMENT
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.FACT_PAYMENTS P ON O.ORDER_ID = P.ORDER_ID
JOIN ECOM_DEV_DB.GOLD.DIM_CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.NAME;

-- ============================================================
-- VIEW NAME: VW_AVG_CUSTOMER_SPEND_ANALYTICS
-- PURPOSE: Calculate average spend per customer
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_AVG_CUSTOMER_SPEND_ANALYTICS AS
SELECT
    ROUND(SUM(P.AMOUNT) / NULLIF(COUNT(DISTINCT C.CUSTOMER_ID),0), 2) AS AVG_SPEND_PER_CUSTOMER,
    COUNT(DISTINCT C.CUSTOMER_ID) AS TOTAL_CUSTOMERS,
    SUM(P.AMOUNT) AS TOTAL_REVENUE
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.FACT_PAYMENTS P ON O.ORDER_ID = P.ORDER_ID
JOIN ECOM_DEV_DB.GOLD.DIM_CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID;

-- ============================================================
-- VIEW NAME: VW_CUSTOMER_ACQ_COST_ANALYTICS
-- PURPOSE: Estimate acquisition cost per customer
-- NOTE: Assumes marketing spend table exists
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_CUSTOMER_ACQ_COST_ANALYTICS AS
SELECT
    M.MONTH,
    SUM(M.SPEND) / NULLIF(COUNT(DISTINCT C.CUSTOMER_ID),0) AS ACQ_COST_PER_CUSTOMER
FROM ECOM_DEV_DB.GOLD.MARKETING_SPEND M
JOIN ECOM_DEV_DB.GOLD.DIM_CUSTOMERS C 
    ON TO_CHAR(C.CREATED_AT, 'YYYY-MM') = M.MONTH
GROUP BY M.MONTH
ORDER BY M.MONTH;

-- ============================================================
-- VIEW NAME: VW_CUSTOMER_RETENTION_ANALYTICS
-- PURPOSE: Measure retention rate of customers month-over-month
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_CUSTOMER_RETENTION_ANALYTICS AS
SELECT
    CUR.MONTH,
    ROUND(
        COUNT(DISTINCT CUR.CUSTOMER_ID) 
        / NULLIF(COUNT(DISTINCT PREV.CUSTOMER_ID),0) * 100, 2
    ) AS RETENTION_RATE_PERCENT
FROM (
    SELECT CUSTOMER_ID, TO_CHAR(ORDER_DATE, 'YYYY-MM') AS MONTH
    FROM ECOM_DEV_DB.GOLD.FACT_ORDERS
) CUR
LEFT JOIN (
    SELECT CUSTOMER_ID, TO_CHAR(ORDER_DATE, 'YYYY-MM') AS MONTH
    FROM ECOM_DEV_DB.GOLD.FACT_ORDERS
) PREV
ON CUR.CUSTOMER_ID = PREV.CUSTOMER_ID
AND CUR.MONTH = TO_CHAR(ADD_MONTHS(TO_DATE(PREV.MONTH,'YYYY-MM'),1),'YYYY-MM')
GROUP BY CUR.MONTH
ORDER BY CUR.MONTH;

-- ============================================================
-- VIEW NAME: VW_CUSTOMER_AGE_GROUP_ANALYTICS
-- PURPOSE: Analyze revenue by customer age group
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_CUSTOMER_AGE_GROUP_ANALYTICS AS
SELECT
    CASE 
        WHEN C.AGE < 25 THEN 'Under 25'
        WHEN C.AGE BETWEEN 25 AND 40 THEN '25-40'
        WHEN C.AGE BETWEEN 41 AND 60 THEN '41-60'
        ELSE '60+'
    END AS AGE_GROUP,
    SUM(P.AMOUNT) AS TOTAL_REVENUE,
    COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.FACT_PAYMENTS P ON O.ORDER_ID = P.ORDER_ID
JOIN ECOM_DEV_DB.GOLD.DIM_CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY AGE_GROUP
ORDER BY TOTAL_REVENUE DESC;

-- ============================================================
-- VIEW NAME: VW_VIP_CUSTOMERS_ANALYTICS
-- PURPOSE: Identify VIP customers based on spend threshold
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_VIP_CUSTOMERS_ANALYTICS AS
SELECT
    C.CUSTOMER_ID,
    C.NAME AS CUSTOMER_NAME,
    SUM(P.AMOUNT) AS TOTAL_SPEND
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.FACT_PAYMENTS P ON O.ORDER_ID = P.ORDER_ID
JOIN ECOM_DEV_DB.GOLD.DIM_CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.NAME
HAVING SUM(P.AMOUNT) >= 10000
ORDER BY TOTAL_SPEND DESC;

-- ============================================================
-- VIEW NAME: VW_CUSTOMER_LIFETIME_VALUE_ANALYTICS
-- PURPOSE: Estimate customer lifetime value (CLV) based on total spend
-- SOURCE: GOLD layer fact (Orders + Payments) and dimension (Customers)
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_CUSTOMER_LIFETIME_VALUE_ANALYTICS AS
SELECT
    C.CUSTOMER_ID,
    C.NAME AS CUSTOMER_NAME,
    SUM(P.AMOUNT) AS TOTAL_SPEND,
    COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS,
    ROUND(SUM(P.AMOUNT) / NULLIF(COUNT(DISTINCT O.ORDER_ID),0), 2) AS AVG_ORDER_VALUE,
    ROUND(SUM(P.AMOUNT) / NULLIF(MONTHS_BETWEEN(CURRENT_DATE, MIN(O.ORDER_DATE)),0), 2) AS AVG_MONTHLY_VALUE
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.FACT_PAYMENTS P 
    ON O.ORDER_ID = P.ORDER_ID
JOIN ECOM_DEV_DB.GOLD.DIM_CUSTOMERS C 
    ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.NAME
ORDER BY TOTAL_SPEND DESC;

-- ============================================================
-- VIEW NAME: VW_CUSTOMER_COHORT_ANALYTICS
-- PURPOSE: Analyze customer cohorts based on their first purchase month
-- SOURCE: GOLD layer fact (Orders) and dimension (Customers)
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_CUSTOMER_COHORT_ANALYTICS AS
WITH FIRST_ORDER AS (
    SELECT
        CUSTOMER_ID,
        MIN(ORDER_DATE) AS FIRST_ORDER_DATE
    FROM ECOM_DEV_DB.GOLD.FACT_ORDERS
    GROUP BY CUSTOMER_ID
),
COHORTS AS (
    SELECT
        FO.CUSTOMER_ID,
        TO_CHAR(FO.FIRST_ORDER_DATE, 'YYYY-MM') AS COHORT_MONTH,
        TO_CHAR(O.ORDER_DATE, 'YYYY-MM') AS ORDER_MONTH,
        COUNT(DISTINCT O.ORDER_ID) AS ORDERS_IN_MONTH,
        SUM(P.AMOUNT) AS REVENUE_IN_MONTH
    FROM FIRST_ORDER FO
    JOIN ECOM_DEV_DB.GOLD.FACT_ORDERS O 
        ON FO.CUSTOMER_ID = O.CUSTOMER_ID
    JOIN ECOM_DEV_DB.GOLD.FACT_PAYMENTS P 
        ON O.ORDER_ID = P.ORDER_ID
    GROUP BY FO.CUSTOMER_ID, TO_CHAR(FO.FIRST_ORDER_DATE, 'YYYY-MM'), TO_CHAR(O.ORDER_DATE, 'YYYY-MM')
)
SELECT
    COHORT_MONTH,
    ORDER_MONTH,
    COUNT(DISTINCT CUSTOMER_ID) AS ACTIVE_CUSTOMERS,
    SUM(ORDERS_IN_MONTH) AS TOTAL_ORDERS,
    SUM(REVENUE_IN_MONTH) AS TOTAL_REVENUE
FROM COHORTS
GROUP BY COHORT_MONTH, ORDER_MONTH
ORDER BY COHORT_MONTH, ORDER_MONTH;