-- analytics layer 
-- Sales & Revenue views 
-- ============================================================
-- VIEW NAME: VW_TOP_PRODUCTS_ANALYTICS
-- PURPOSE: Identify top-selling products based on total revenue
-- SOURCE: GOLD layer fact and dimension tables
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_TOP_PRODUCTS_ANALYTICS AS
SELECT
    P.PRODUCT_ID,
    P.NAME AS PRODUCT_NAME,
    P.CATEGORY,
    SUM(O.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS,
    SUM(O.TOTAL_AMOUNT) / COUNT(DISTINCT O.ORDER_ID) AS AVG_ORDER_VALUE
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.DIM_PRODUCTS P
    ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.NAME, P.CATEGORY
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

-- ============================================================
-- VIEW NAME: VW_MONTHLY_REVENUE_ANALYTICS
-- PURPOSE: Calculate total revenue and order count per month
-- SOURCE: GOLD layer fact tables (Orders + Payments)
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_MONTHLY_REVENUE_ANALYTICS AS
SELECT
    TO_CHAR(O.ORDER_DATE, 'YYYY-MM') AS MONTH,
    SUM(P.AMOUNT) AS TOTAL_REVENUE,
    COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS,
    ROUND(SUM(P.AMOUNT) / NULLIF(COUNT(DISTINCT O.ORDER_ID),0), 2) AS AVG_ORDER_VALUE
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.FACT_PAYMENTS P
    ON O.ORDER_ID = P.ORDER_ID
GROUP BY TO_CHAR(O.ORDER_DATE, 'YYYY-MM')
ORDER BY MONTH;

-- ============================================================
-- VIEW NAME: VW_REVENUE_BY_CATEGORY_ANALYTICS
-- PURPOSE: Calculate total revenue and order count by product category
-- SOURCE: GOLD layer fact (Orders) and dimension (Products)
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_REVENUE_BY_CATEGORY_ANALYTICS AS
SELECT
    P.CATEGORY AS PRODUCT_CATEGORY,
    SUM(O.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS,
    ROUND(SUM(O.TOTAL_AMOUNT) / NULLIF(COUNT(DISTINCT O.ORDER_ID),0), 2) AS AVG_ORDER_VALUE
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.DIM_PRODUCTS P
    ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

-- ============================================================
-- VIEW NAME: VW_REVENUE_BY_CURRENCY_ANALYTICS
-- PURPOSE: Calculate total revenue and order count by currency
-- SOURCE: GOLD layer fact (Payments) and dimension (Products)
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_REVENUE_BY_CURRENCY_ANALYTICS AS
SELECT
    P.CURRENCY AS TRANSACTION_CURRENCY,
    SUM(P.AMOUNT) AS TOTAL_REVENUE,
    COUNT(DISTINCT P.PAYMENT_ID) AS TOTAL_PAYMENTS,
    ROUND(SUM(P.AMOUNT) / NULLIF(COUNT(DISTINCT P.PAYMENT_ID),0), 2) AS AVG_PAYMENT_VALUE
FROM ECOM_DEV_DB.GOLD.FACT_PAYMENTS P
GROUP BY P.CURRENCY
ORDER BY TOTAL_REVENUE DESC;

-- ============================================================
-- VIEW NAME: VW_REVENUE_BY_COUNTRY_ANALYTICS
-- PURPOSE: Calculate total revenue and order count by customer country
-- SOURCE: GOLD layer fact (Orders + Payments) and dimension (Customers)
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_REVENUE_BY_COUNTRY_ANALYTICS AS
SELECT
    C.COUNTRY AS CUSTOMER_COUNTRY,
    SUM(P.AMOUNT) AS TOTAL_REVENUE,
    COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS,
    ROUND(SUM(P.AMOUNT) / NULLIF(COUNT(DISTINCT O.ORDER_ID),0), 2) AS AVG_ORDER_VALUE
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.FACT_PAYMENTS P
    ON O.ORDER_ID = P.ORDER_ID
JOIN ECOM_DEV_DB.GOLD.DIM_CUSTOMERS C
    ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.COUNTRY
ORDER BY TOTAL_REVENUE DESC;

-- ============================================================
-- VIEW NAME: VW_AVG_ORDER_VALUE_ANALYTICS
-- PURPOSE: Calculate average order value across all orders
-- SOURCE: GOLD layer fact tables (Orders + Payments)
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_AVG_ORDER_VALUE_ANALYTICS AS
SELECT
    ROUND(SUM(P.AMOUNT) / NULLIF(COUNT(DISTINCT O.ORDER_ID),0), 2) AS AVG_ORDER_VALUE,
    COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS,
    SUM(P.AMOUNT) AS TOTAL_REVENUE
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.FACT_PAYMENTS P
    ON O.ORDER_ID = P.ORDER_ID;

    -- ============================================================
-- VIEW NAME: VW_SALES_BY_EMPLOYEE_ANALYTICS
-- PURPOSE: Show sales performance by employee
-- SOURCE: GOLD layer fact (Orders) and dimension (Employees)
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_SALES_BY_EMPLOYEE_ANALYTICS AS
SELECT
    E.EMPLOYEE_ID,
    E.NAME AS EMPLOYEE_NAME,
    E.DEPARTMENT,
    COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS,
    SUM(O.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.DIM_EMPLOYEES E
    ON O.EMPLOYEE_ID = E.EMPLOYEE_ID
GROUP BY E.EMPLOYEE_ID, E.NAME, E.DEPARTMENT
ORDER BY TOTAL_REVENUE DESC;

-- ============================================================
-- VIEW NAME: VW_FASTEST_GROWING_COUNTRIES_ANALYTICS
-- PURPOSE: Identify countries with fastest revenue growth month-over-month
-- SOURCE: GOLD layer fact (Orders + Payments) and dimension (Customers)
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_FASTEST_GROWING_COUNTRIES_ANALYTICS AS
SELECT
    C.COUNTRY,
    TO_CHAR(O.ORDER_DATE, 'YYYY-MM') AS MONTH,
    SUM(P.AMOUNT) AS TOTAL_REVENUE,
    LAG(SUM(P.AMOUNT)) OVER (PARTITION BY C.COUNTRY ORDER BY TO_CHAR(O.ORDER_DATE, 'YYYY-MM')) AS PREV_MONTH_REVENUE,
    ROUND(
        (SUM(P.AMOUNT) - LAG(SUM(P.AMOUNT)) OVER (PARTITION BY C.COUNTRY ORDER BY TO_CHAR(O.ORDER_DATE, 'YYYY-MM')))
        / NULLIF(LAG(SUM(P.AMOUNT)) OVER (PARTITION BY C.COUNTRY ORDER BY TO_CHAR(O.ORDER_DATE, 'YYYY-MM')),0) * 100, 2
    ) AS GROWTH_PERCENT
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.FACT_PAYMENTS P
    ON O.ORDER_ID = P.ORDER_ID
JOIN ECOM_DEV_DB.GOLD.DIM_CUSTOMERS C
    ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.COUNTRY, TO_CHAR(O.ORDER_DATE, 'YYYY-MM')
ORDER BY GROWTH_PERCENT DESC;

-- ============================================================
-- VIEW NAME: VW_SEASONAL_SALES_ANALYTICS
-- PURPOSE: Analyze sales by season (quarter-based)
-- SOURCE: GOLD layer fact (Orders + Payments)
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_SEASONAL_SALES_ANALYTICS AS
SELECT
    CASE 
        WHEN EXTRACT(MONTH FROM O.ORDER_DATE) IN (12,1,2) THEN 'Winter'
        WHEN EXTRACT(MONTH FROM O.ORDER_DATE) IN (3,4,5) THEN 'Spring'
        WHEN EXTRACT(MONTH FROM O.ORDER_DATE) IN (6,7,8) THEN 'Summer'
        WHEN EXTRACT(MONTH FROM O.ORDER_DATE) IN (9,10,11) THEN 'Fall'
    END AS SEASON,
    SUM(P.AMOUNT) AS TOTAL_REVENUE,
    COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.FACT_PAYMENTS P
    ON O.ORDER_ID = P.ORDER_ID
GROUP BY SEASON
ORDER BY TOTAL_REVENUE DESC;

-- ============================================================
-- VIEW NAME: VW_PROMOTION_IMPACT_ANALYTICS
-- PURPOSE: Measure impact of promotions on sales
-- SOURCE: GOLD layer fact (Orders) and dimension (Products)
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_PROMOTION_IMPACT_ANALYTICS AS
SELECT
    O.PROMOTION_ID,
    COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS,
    SUM(O.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    ROUND(SUM(O.TOTAL_AMOUNT) / NULLIF(COUNT(DISTINCT O.ORDER_ID),0), 2) AS AVG_ORDER_VALUE
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
WHERE O.PROMOTION_ID IS NOT NULL
GROUP BY O.PROMOTION_ID
ORDER BY TOTAL_REVENUE DESC;