-- Finance & Risk
-- ============================================================
-- VIEW NAME: VW_PAYMENT_SUCCESS_RATE_ANALYTICS
-- PURPOSE: Calculate payment success vs. failure rate
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_PAYMENT_SUCCESS_RATE_ANALYTICS AS
SELECT
    P.PAYMENT_METHOD,
    COUNT(CASE WHEN UPPER(P.STATUS) = 'SUCCESS' THEN 1 END) AS SUCCESS_COUNT,
    COUNT(CASE WHEN UPPER(P.STATUS) = 'FAILED' THEN 1 END) AS FAILURE_COUNT,
    ROUND(
        COUNT(CASE WHEN UPPER(P.STATUS) = 'SUCCESS' THEN 1 END) 
        / NULLIF(COUNT(P.PAYMENT_ID),0) * 100, 2
    ) AS SUCCESS_RATE_PERCENT
FROM ECOM_DEV_DB.GOLD.FACT_PAYMENTS P
GROUP BY P.PAYMENT_METHOD
ORDER BY SUCCESS_RATE_PERCENT DESC;

-- ============================================================
-- VIEW NAME: VW_CURRENCY_EXCHANGE_IMPACT_ANALYTICS
-- PURPOSE: Measure impact of currency exchange on revenue
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_CURRENCY_EXCHANGE_IMPACT_ANALYTICS AS
SELECT
    P.CURRENCY,
    SUM(P.AMOUNT) AS TOTAL_REVENUE,
    ROUND(SUM(P.AMOUNT * FX.EXCHANGE_RATE), 2) AS REVENUE_IN_BASE_CURRENCY
FROM ECOM_DEV_DB.GOLD.FACT_PAYMENTS P
JOIN ECOM_DEV_DB.GOLD.DIM_EXCHANGE_RATES FX ON P.CURRENCY = FX.CURRENCY
GROUP BY P.CURRENCY
ORDER BY REVENUE_IN_BASE_CURRENCY DESC;

-- ============================================================
-- VIEW NAME: VW_FRAUD_DETECTION_ANALYTICS
-- PURPOSE: Flag suspicious orders (high value or mismatched data)
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_FRAUD_DETECTION_ANALYTICS AS
SELECT
    O.ORDER_ID,
    O.CUSTOMER_ID,
    O.TOTAL_AMOUNT,
    P.PAYMENT_METHOD,
    CASE 
        WHEN O.TOTAL_AMOUNT > 10000 THEN 'High Value'
        WHEN O.CUSTOMER_ID IS NULL THEN 'Missing Customer'
        WHEN P.PAYMENT_METHOD IS NULL THEN 'Missing Payment Method'
        ELSE 'Potential Fraud'
    END AS FRAUD_REASON
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
LEFT JOIN ECOM_DEV_DB.GOLD.FACT_PAYMENTS P ON O.ORDER_ID = P.ORDER_ID
WHERE O.TOTAL_AMOUNT > 10000 
   OR O.CUSTOMER_ID IS NULL 
   OR P.PAYMENT_METHOD IS NULL;

   -- ============================================================
-- VIEW NAME: VW_LOGISTICS_COST_ANALYTICS
-- PURPOSE: Track logistics costs by carrier
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_LOGISTICS_COST_ANALYTICS AS
SELECT
    S.CARRIER,
    SUM(S.COST) AS TOTAL_LOGISTICS_COST,
    COUNT(DISTINCT S.SHIPMENT_ID) AS TOTAL_SHIPMENTS,
    ROUND(SUM(S.COST) / NULLIF(COUNT(DISTINCT S.SHIPMENT_ID),0), 2) AS AVG_COST_PER_SHIPMENT
FROM ECOM_DEV_DB.GOLD.FACT_SHIPMENTS S
GROUP BY S.CARRIER
ORDER BY TOTAL_LOGISTICS_COST DESC;

-- ============================================================
-- VIEW NAME: VW_EMPLOYEE_PRODUCTIVITY_ANALYTICS
-- PURPOSE: Measure employee productivity based on orders handled
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_EMPLOYEE_PRODUCTIVITY_ANALYTICS AS
SELECT
    E.EMPLOYEE_ID,
    E.NAME AS EMPLOYEE_NAME,
    COUNT(DISTINCT O.ORDER_ID) AS ORDERS_HANDLED,
    SUM(O.TOTAL_AMOUNT) AS REVENUE_HANDLED
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.DIM_EMPLOYEES E ON O.EMPLOYEE_ID = E.EMPLOYEE_ID
GROUP BY E.EMPLOYEE_ID, E.NAME
ORDER BY ORDERS_HANDLED DESC;

-- ============================================================
-- VIEW NAME: VW_COUNTRY_PROFITABILITY_ANALYTICS
-- PURPOSE: Calculate profitability by country
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_COUNTRY_PROFITABILITY_ANALYTICS AS
SELECT
    C.COUNTRY,
    SUM(P.AMOUNT) AS TOTAL_REVENUE,
    SUM(O.COST) AS TOTAL_COST,
    (SUM(P.AMOUNT) - SUM(O.COST)) AS PROFIT
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.FACT_PAYMENTS P ON O.ORDER_ID = P.ORDER_ID
JOIN ECOM_DEV_DB.GOLD.DIM_CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.COUNTRY
ORDER BY PROFIT DESC;

-- ============================================================
-- VIEW NAME: VW_CAMPAIGN_ROI_ANALYTICS
-- PURPOSE: Measure ROI of marketing campaigns
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_CAMPAIGN_ROI_ANALYTICS AS
SELECT
    M.CAMPAIGN_ID,
    M.CAMPAIGN_NAME,
    SUM(P.AMOUNT) AS REVENUE,
    SUM(M.SPEND) AS COST,
    ROUND((SUM(P.AMOUNT) - SUM(M.SPEND)) / NULLIF(SUM(M.SPEND),0) * 100, 2) AS ROI_PERCENT
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.FACT_PAYMENTS P ON O.ORDER_ID = P.ORDER_ID
JOIN ECOM_DEV_DB.GOLD.FACT_MARKETING M ON O.CAMPAIGN_ID = M.CAMPAIGN_ID
GROUP BY M.CAMPAIGN_ID, M.CAMPAIGN_NAME
ORDER BY ROI_PERCENT DESC;

-- ============================================================
-- VIEW NAME: VW_OPERATIONAL_EFFICIENCY_ANALYTICS
-- PURPOSE: Track operational efficiency (orders per employee)
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_OPERATIONAL_EFFICIENCY_ANALYTICS AS
SELECT
    E.DEPARTMENT,
    COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS,
    COUNT(DISTINCT E.EMPLOYEE_ID) AS TOTAL_EMPLOYEES,
    ROUND(COUNT(DISTINCT O.ORDER_ID) / NULLIF(COUNT(DISTINCT E.EMPLOYEE_ID),0), 2) AS ORDERS_PER_EMPLOYEE
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.DIM_EMPLOYEES E ON O.EMPLOYEE_ID = E.EMPLOYEE_ID
GROUP BY E.DEPARTMENT
ORDER BY ORDERS_PER_EMPLOYEE DESC;

-- ============================================================
-- VIEW NAME: VW_REFUND_PROCESSING_TIME_ANALYTICS
-- PURPOSE: Measure average refund processing time
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_REFUND_PROCESSING_TIME_ANALYTICS AS
SELECT
    R.RETURN_ID,
    R.ORDER_ID,
    R.RETURN_DATE,
    R.REFUND_DATE,
    (R.REFUND_DATE - R.RETURN_DATE) AS PROCESSING_DAYS
FROM ECOM_DEV_DB.GOLD.FACT_RETURNS R
ORDER BY PROCESSING_DAYS DESC;

-- ============================================================
-- VIEW NAME: VW_COMPLIANCE_CHECKS_ANALYTICS
-- PURPOSE: Track compliance issues in orders
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_COMPLIANCE_CHECKS_ANALYTICS AS
SELECT
    O.ORDER_ID,
    O.CUSTOMER_ID,
    O.ORDER_DATE,
    CASE 
        WHEN O.TOTAL_AMOUNT <= 0 THEN 'Invalid Amount'
        WHEN O.CUSTOMER_ID IS NULL THEN 'Missing Customer'
        ELSE 'Compliant'
    END AS COMPLIANCE_STATUS
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O;

-- ============================================================
-- VIEW NAME: VW_CHANNEL_PERFORMANCE_ANALYTICS
-- PURPOSE: Compare performance across sales channels
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_CHANNEL_PERFORMANCE_ANALYTICS AS
SELECT
    O.CHANNEL,
    COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS,
    SUM(P.AMOUNT) AS TOTAL_REVENUE,
    ROUND(SUM(P.AMOUNT) / NULLIF(COUNT(DISTINCT O.ORDER_ID),0), 2) AS AVG_ORDER_VALUE
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.FACT_PAYMENTS P ON O.ORDER_ID = P.ORDER_ID
GROUP BY O.CHANNEL
ORDER BY TOTAL_REVENUE DESC;

-- ============================================================
-- VIEW NAME: VW_CAMPAIGN_CONVERSION_ANALYTICS
-- PURPOSE: Measure conversion rate of marketing campaigns
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_CAMPAIGN_CONVERSION_ANALYTICS AS
SELECT
    M.CAMPAIGN_ID,
    M.CAMPAIGN_NAME,
    COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS,
    COUNT(DISTINCT C.CUSTOMER_ID) AS TOTAL_CUSTOMERS,
    ROUND(COUNT(DISTINCT O.ORDER_ID) / NULLIF(COUNT(DISTINCT C.CUSTOMER_ID),0) * 100, 2) AS CONVERSION_RATE_PERCENT
FROM ECOM_DEV_DB.GOLD.FACT_ORDERS O
JOIN ECOM_DEV_DB.GOLD.DIM_CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
JOIN ECOM_DEV_DB.GOLD.FACT_MARKETING M ON O.CAMPAIGN_ID = M.CAMPAIGN_ID
GROUP BY M.CAMPAIGN_ID, M.CAMPAIGN_NAME
ORDER BY CONVERSION_RATE_PERCENT DESC;

-- ============================================================
-- VIEW NAME: VW_SUSTAINABILITY_IMPACT_ANALYTICS
-- PURPOSE: Track sustainability impact (e.g., eco-friendly shipments)
-- ============================================================

CREATE OR REPLACE VIEW ECOM_DEV_DB.ANALYTICS.VW_SUSTAINABILITY_IMPACT_ANALYTICS AS
SELECT
    S.CARRIER,
    COUNT(DISTINCT S.SHIPMENT_ID) AS TOTAL_SHIPMENTS,
    SUM(S.CO2_EMISSIONS) AS TOTAL_CO2_EMISSIONS,
    ROUND(AVG(S.CO2_EMISSIONS), 2) AS AVG_CO2_PER_SHIPMENT
FROM ECOM_DEV_DB.GOLD.FACT_SHIPMENTS S
GROUP BY S.CARRIER
ORDER BY TOTAL_CO2_EMISSIONS ASC;
