-- #######################################################################
-- ########   RAW SCHEMA FROM STAGES TO RAW_TABLES  ######################
-- #######################################################################

-- CUSTOMERS
COPY INTO ECOM_DEV_DB.RAW.RAW_CUSTOMERS
FROM @ECOM_DEV_DB.RAW.RAW_DATA/raw/ecommerce/customers/full/2026/06/04/customers_full_20260604_001.csv
FILE_FORMAT = (FORMAT_NAME = ECOM_DEV_DB.RAW.CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

-- ORDERS
COPY INTO ECOM_DEV_DB.RAW.RAW_ORDERS
FROM @ECOM_DEV_DB.RAW.RAW_DATA/raw/ecommerce/orders/full/2026/06/04/orders_full_20260604_001.csv
FILE_FORMAT = (FORMAT_NAME = ECOM_DEV_DB.RAW.CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

-- PAYMENTS
COPY INTO ECOM_DEV_DB.RAW.RAW_PAYMENTS
FROM @ECOM_DEV_DB.RAW.RAW_DATA/raw/ecommerce/payments/full/2026/06/04/payments_full_20260604_001.csv
FILE_FORMAT = (FORMAT_NAME = ECOM_DEV_DB.RAW.CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

-- SHIPMENTS
COPY INTO ECOM_DEV_DB.RAW.RAW_SHIPMENTS
FROM @ECOM_DEV_DB.RAW.RAW_DATA/raw/ecommerce/shipments/full/2026/06/04/shipments_full_20260604_001.csv
FILE_FORMAT = (FORMAT_NAME = ECOM_DEV_DB.RAW.CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

-- PRODUCTS
COPY INTO ECOM_DEV_DB.RAW.RAW_PRODUCTS
FROM @ECOM_DEV_DB.RAW.RAW_DATA/raw/ecommerce/products/full/2026/06/04/products_full_20260604_001.csv
FILE_FORMAT = (FORMAT_NAME = ECOM_DEV_DB.RAW.CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';

-- EMPLOYEES
COPY INTO ECOM_DEV_DB.RAW.RAW_EMPLOYEES
FROM @ECOM_DEV_DB.RAW.RAW_DATA/raw/ecommerce/employees/full/2026/06/04/employees_full_20260604_001.csv
FILE_FORMAT = (FORMAT_NAME = ECOM_DEV_DB.RAW.CSV_FILE_FORMAT)
ON_ERROR = 'CONTINUE';