    -- =====================================================================
-- STAGE TO CLEAN : CUSTOMERS
-- =====================================================================

-- STEP : SEND REJECTED RECORDS TO DQ
INSERT INTO ECOM_DEV_DB.DQ.DQ_ERROR_LOG
(
    PIPELINE_NAME,
    LAYER_NAME,
    TABLE_NAME,
    BUSINESS_KEY,
    ERROR_TYPE,
    ERROR_MESSAGE,
    LOAD_TIMESTAMP,
    RAW_RECORD
)
SELECT
    'CUSTOMER_PIPELINE',
    'STAGE_TO_CLEAN',
    'STAGE_CUSTOMERS',
    CUSTOMER_ID,
    CASE
        WHEN CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM TEMP_CONFLICTING_CUSTOMERS)
            THEN 'CONFLICTING_CUSTOMER_RECORD'
        WHEN COUNT(*) OVER(PARTITION BY EMAIL) > 1
            THEN 'DUPLICATE_EMAIL'
    END AS ERROR_TYPE,
    CASE
        WHEN CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM TEMP_CONFLICTING_CUSTOMERS)
            THEN 'SAME CUSTOMER_ID HAS MULTIPLE DIFFERENT RECORDS'
        WHEN COUNT(*) OVER(PARTITION BY EMAIL) > 1
            THEN 'EMAIL IS ASSOCIATED WITH MULTIPLE CUSTOMERS'
    END AS ERROR_MESSAGE,
    CURRENT_TIMESTAMP(),
    OBJECT_CONSTRUCT(*)
FROM TEMP_CUSTOMERS_STEP2
QUALIFY CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM TEMP_CONFLICTING_CUSTOMERS)
    OR COUNT(*) OVER(PARTITION BY EMAIL) > 1;

-- STEP 1 : REMOVE NULLS, BLANKS, TEST DATA
CREATE OR REPLACE TEMP TABLE TEMP_CUSTOMERS_STEP1 AS
SELECT *
FROM ECOM_DEV_DB.STAGE.STAGE_CUSTOMERS
WHERE CUSTOMER_ID IS NOT NULL
  AND NAME IS NOT NULL
  AND EMAIL IS NOT NULL
  AND PHONE IS NOT NULL
  AND COUNTRY IS NOT NULL
  AND CREATED_AT IS NOT NULL
  AND TRIM(NAME) <> ''
  AND TRIM(EMAIL) <> ''
  AND TRIM(PHONE) <> ''
  AND UPPER(NAME) NOT LIKE '%TEST%'
  AND UPPER(NAME) NOT LIKE '%DUMMY%'
  AND CREATED_AT <= CURRENT_DATE();

-- STEP 2 : FIND DUPLICATE CUSTOMER IDS
CREATE OR REPLACE TEMP TABLE TEMP_DUP_CUSTOMERS AS
SELECT CUSTOMER_ID
FROM TEMP_CUSTOMERS_STEP1
GROUP BY CUSTOMER_ID
HAVING COUNT(*) > 1;

-- STEP 3 : REMOVE CONFLICTING DUPLICATES
CREATE OR REPLACE TEMP TABLE TEMP_CUSTOMERS_STEP2 AS
SELECT DISTINCT CUSTOMER_ID, NAME, EMAIL, PHONE, COUNTRY, CREATED_AT
FROM TEMP_CUSTOMERS_STEP1;

-- STEP 4 : REMOVE CUSTOMER IDS HAVING DIFFERENT DATA
CREATE OR REPLACE TEMP TABLE TEMP_CUSTOMERS_STEP3 AS
SELECT *
FROM TEMP_CUSTOMERS_STEP2
WHERE CUSTOMER_ID NOT IN (
    SELECT CUSTOMER_ID
    FROM (
        SELECT CUSTOMER_ID,
               COUNT(*) AS TOTAL_ROWS,
               COUNT(DISTINCT CONCAT(NAME,EMAIL,PHONE,COUNTRY,CREATED_AT)) AS UNIQUE_ROWS
        FROM TEMP_CUSTOMERS_STEP2
        GROUP BY CUSTOMER_ID
    ) X
    WHERE TOTAL_ROWS <> UNIQUE_ROWS
);

-- STEP 5 : HANDLE DUPLICATE EMAILS
CREATE OR REPLACE TEMP TABLE TEMP_CUSTOMERS_STEP4 AS
SELECT CUSTOMER_ID,
       NAME,
       CASE WHEN COUNT(*) OVER (PARTITION BY EMAIL) > 1 THEN 'N/A' ELSE EMAIL END AS EMAIL,
       PHONE,
       COUNTRY,
       CREATED_AT
FROM TEMP_CUSTOMERS_STEP3;

-- STEP 6 : KEEP ONLY ONE ROW PER CUSTOMER_ID
CREATE OR REPLACE TEMP TABLE TEMP_CUSTOMERS_FINAL AS
SELECT *
FROM TEMP_CUSTOMERS_STEP4
QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY CREATED_AT DESC) = 1;

-- STEP 7 : LOAD CLEAN TABLE
INSERT INTO ECOM_DEV_DB.CLEAN.CUSTOMERS_CLEAN
(
    CUSTOMER_ID,
    NAME,
    EMAIL,
    PHONE,
    COUNTRY,
    CREATED_AT
)
SELECT CUSTOMER_ID, NAME, EMAIL, PHONE, COUNTRY, CREATED_AT
FROM TEMP_CUSTOMERS_FINAL;

-- =====================================================================
-- STAGE TO CLEAN : ORDERS
-- =====================================================================

-- STEP 1 : REMOVE NULLS / BLANKS / INVALID DATA
CREATE OR REPLACE TEMP TABLE TEMP_ORDERS_STEP1 AS
SELECT *
FROM ECOM_DEV_DB.STAGE.STAGE_ORDERS
WHERE ORDER_ID IS NOT NULL
  AND CUSTOMER_ID IS NOT NULL
  AND ORDER_DATE IS NOT NULL
  AND STATUS IS NOT NULL AND TRIM(STATUS) <> ''
  AND TOTAL_AMOUNT IS NOT NULL AND TOTAL_AMOUNT >= 0
  AND PAYMENT_ID IS NOT NULL
  AND SHIPMENT_ID IS NOT NULL
  AND ORDER_DATE <= CURRENT_DATE();

-- STEP 2 : REMOVE EXACT DUPLICATE RECORDS
CREATE OR REPLACE TEMP TABLE TEMP_ORDERS_STEP2 AS
SELECT DISTINCT ORDER_ID, CUSTOMER_ID, ORDER_DATE, STATUS, TOTAL_AMOUNT, PAYMENT_ID, SHIPMENT_ID
FROM TEMP_ORDERS_STEP1;

-- STEP 3 : FIND CONFLICTING ORDER IDS
CREATE OR REPLACE TEMP TABLE TEMP_BAD_ORDER_IDS AS
SELECT ORDER_ID
FROM (
    SELECT ORDER_ID,
           COUNT(*) AS TOTAL_ROWS,
           COUNT(DISTINCT CONCAT(CUSTOMER_ID,ORDER_DATE,STATUS,TOTAL_AMOUNT,PAYMENT_ID,SHIPMENT_ID)) AS UNIQUE_ROWS
    FROM TEMP_ORDERS_STEP2
    GROUP BY ORDER_ID
) X
WHERE TOTAL_ROWS <> UNIQUE_ROWS;

-- STEP 4 : FIND DUPLICATE PAYMENT IDS
CREATE OR REPLACE TEMP TABLE TEMP_BAD_PAYMENT_IDS AS
SELECT PAYMENT_ID
FROM TEMP_ORDERS_STEP2
GROUP BY PAYMENT_ID
HAVING COUNT(*) > 1;

-- STEP 5 : FIND DUPLICATE SHIPMENT IDS
CREATE OR REPLACE TEMP TABLE TEMP_BAD_SHIPMENT_IDS AS
SELECT SHIPMENT_ID
FROM TEMP_ORDERS_STEP2
GROUP BY SHIPMENT_ID
HAVING COUNT(*) > 1;

-- STEP 6 : REMOVE ALL INVALID RECORDS
CREATE OR REPLACE TEMP TABLE TEMP_ORDERS_FINAL AS
SELECT *
FROM TEMP_ORDERS_STEP2
WHERE ORDER_ID NOT IN (SELECT ORDER_ID FROM TEMP_BAD_ORDER_IDS)
  AND PAYMENT_ID NOT IN (SELECT PAYMENT_ID FROM TEMP_BAD_PAYMENT_IDS)
  AND SHIPMENT_ID NOT IN (SELECT SHIPMENT_ID FROM TEMP_BAD_SHIPMENT_IDS);

-- STEP 7 : LOAD INTO CLEAN TABLE
INSERT INTO ECOM_DEV_DB.CLEAN.ORDERS_CLEAN
(
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_DATE,
    STATUS,
    TOTAL_AMOUNT,
    PAYMENT_ID,
    SHIPMENT_ID
)
SELECT ORDER_ID, CUSTOMER_ID, ORDER_DATE, STATUS, TOTAL_AMOUNT, PAYMENT_ID, SHIPMENT_ID
FROM TEMP_ORDERS_FINAL;
-- =====================================================================
-- STAGE TO CLEAN : PAYMENTS
-- CLEAN LAYER BUSINESS RULES
-- =====================================================================

-- STEP 1A : INVALID RECORDS TO DQ
INSERT INTO ECOM_DEV_DB.DQ.DQ_ERROR_LOG
(
    PIPELINE_NAME,
    LAYER_NAME,
    TABLE_NAME,
    BUSINESS_KEY,
    ERROR_TYPE,
    ERROR_MESSAGE,
    LOAD_TIMESTAMP,
    RAW_RECORD
)
SELECT
    'PAYMENT_PIPELINE',
    'STAGE_TO_CLEAN',
    'STAGE_PAYMENTS',
    COALESCE(TO_VARCHAR(PAYMENT_ID),'UNKNOWN'),
    CASE
        WHEN PAYMENT_ID IS NULL THEN 'NULL_PAYMENT_ID'
        WHEN ORDER_ID IS NULL THEN 'NULL_ORDER_ID'
        WHEN PAYMENT_METHOD IS NULL OR TRIM(PAYMENT_METHOD) = '' THEN 'INVALID_PAYMENT_METHOD'
        WHEN PAYMENT_DATE IS NULL THEN 'NULL_PAYMENT_DATE'
        WHEN PAYMENT_DATE > CURRENT_DATE() THEN 'FUTURE_PAYMENT_DATE'
        WHEN AMOUNT IS NULL THEN 'NULL_AMOUNT'
        WHEN AMOUNT < 0 THEN 'NEGATIVE_AMOUNT'
        WHEN CURRENCY IS NULL OR TRIM(CURRENCY) = '' THEN 'INVALID_CURRENCY'
    END AS ERROR_TYPE,
    CASE
        WHEN PAYMENT_ID IS NULL THEN 'PAYMENT ID IS NULL'
        WHEN ORDER_ID IS NULL THEN 'ORDER ID IS NULL'
        WHEN PAYMENT_METHOD IS NULL OR TRIM(PAYMENT_METHOD) = '' THEN 'PAYMENT METHOD IS NULL OR BLANK'
        WHEN PAYMENT_DATE IS NULL THEN 'PAYMENT DATE IS NULL'
        WHEN PAYMENT_DATE > CURRENT_DATE() THEN 'PAYMENT DATE CANNOT BE IN FUTURE'
        WHEN AMOUNT IS NULL THEN 'AMOUNT IS NULL'
        WHEN AMOUNT < 0 THEN 'AMOUNT CANNOT BE NEGATIVE'
        WHEN CURRENCY IS NULL OR TRIM(CURRENCY) = '' THEN 'CURRENCY IS NULL OR BLANK'
    END AS ERROR_MESSAGE,
    CURRENT_TIMESTAMP(),
    OBJECT_CONSTRUCT(*)
FROM ECOM_DEV_DB.STAGE.STAGE_PAYMENTS
WHERE PAYMENT_ID IS NULL
   OR ORDER_ID IS NULL
   OR PAYMENT_METHOD IS NULL OR TRIM(PAYMENT_METHOD) = ''
   OR PAYMENT_DATE IS NULL OR PAYMENT_DATE > CURRENT_DATE()
   OR AMOUNT IS NULL OR AMOUNT < 0
   OR CURRENCY IS NULL OR TRIM(CURRENCY) = '';

-- STEP 1B : CONFLICTING PAYMENT IDS TO DQ
INSERT INTO ECOM_DEV_DB.DQ.DQ_ERROR_LOG
(
    PIPELINE_NAME,
    LAYER_NAME,
    TABLE_NAME,
    BUSINESS_KEY,
    ERROR_TYPE,
    ERROR_MESSAGE,
    LOAD_TIMESTAMP,
    RAW_RECORD
)
SELECT
    'PAYMENT_PIPELINE',
    'STAGE_TO_CLEAN',
    'STAGE_PAYMENTS',
    TO_VARCHAR(PAYMENT_ID),
    'CONFLICTING_PAYMENT_RECORD',
    'SAME PAYMENT_ID HAS MULTIPLE DIFFERENT BUSINESS VALUES',
    CURRENT_TIMESTAMP(),
    OBJECT_CONSTRUCT(*)
FROM TEMP_PAYMENTS_STEP2
WHERE PAYMENT_ID IN (SELECT PAYMENT_ID FROM TEMP_BAD_PAYMENT_IDS);

-- STEP 1 : STANDARDIZATION + BASIC VALIDATION
CREATE OR REPLACE TEMP TABLE TEMP_PAYMENTS_STEP1 AS
SELECT
    PAYMENT_ID,
    ORDER_ID,
    UPPER(TRIM(PAYMENT_METHOD)) AS PAYMENT_METHOD,
    PAYMENT_DATE,
    ROUND(AMOUNT, 2) AS AMOUNT,
    UPPER(TRIM(CURRENCY)) AS CURRENCY
FROM ECOM_DEV_DB.STAGE.STAGE_PAYMENTS
WHERE PAYMENT_ID IS NOT NULL
  AND ORDER_ID IS NOT NULL
  AND PAYMENT_METHOD IS NOT NULL AND TRIM(PAYMENT_METHOD) <> ''
  AND PAYMENT_DATE IS NOT NULL AND PAYMENT_DATE <= CURRENT_DATE()
  AND AMOUNT IS NOT NULL AND AMOUNT >= 0
  AND CURRENCY IS NOT NULL AND TRIM(CURRENCY) <> '';

-- STEP 2 : REMOVE EXACT DUPLICATES
CREATE OR REPLACE TEMP TABLE TEMP_PAYMENTS_STEP2 AS
SELECT DISTINCT
    PAYMENT_ID,
    ORDER_ID,
    PAYMENT_METHOD,
    PAYMENT_DATE,
    AMOUNT,
    CURRENCY
FROM TEMP_PAYMENTS_STEP1;

-- STEP 3 : FIND CONFLICTING PAYMENT IDS
CREATE OR REPLACE TEMP TABLE TEMP_BAD_PAYMENT_IDS AS
SELECT PAYMENT_ID
FROM (
    SELECT PAYMENT_ID,
           COUNT(*) AS TOTAL_ROWS,
           COUNT(DISTINCT CONCAT(ORDER_ID,PAYMENT_METHOD,PAYMENT_DATE,AMOUNT,CURRENCY)) AS UNIQUE_ROWS
    FROM TEMP_PAYMENTS_STEP2
    GROUP BY PAYMENT_ID
) X
WHERE TOTAL_ROWS <> UNIQUE_ROWS;

-- STEP 4 : REMOVE ALL BAD PAYMENT IDS
CREATE OR REPLACE TEMP TABLE TEMP_PAYMENTS_FINAL AS
SELECT *
FROM TEMP_PAYMENTS_STEP2
WHERE PAYMENT_ID NOT IN (SELECT PAYMENT_ID FROM TEMP_BAD_PAYMENT_IDS);

-- STEP 5 : LOAD INTO CLEAN TABLE
INSERT INTO ECOM_DEV_DB.CLEAN.PAYMENTS_CLEAN
(
    PAYMENT_ID,
    ORDER_ID,
    PAYMENT_METHOD,
    PAYMENT_DATE,
    AMOUNT,
    CURRENCY
)
SELECT
    PAYMENT_ID,
    ORDER_ID,
    PAYMENT_METHOD,
    PAYMENT_DATE,
    AMOUNT,
    CURRENCY
FROM TEMP_PAYMENTS_FINAL;
-- =====================================================================
-- STAGE TO CLEAN : SHIPMENTS
-- CLEAN LAYER BUSINESS RULES
-- =====================================================================

-- STEP 1A : INVALID SHIPMENT RECORDS TO DQ
INSERT INTO ECOM_DEV_DB.DQ.DQ_ERROR_LOG
(
    PIPELINE_NAME,
    LAYER_NAME,
    TABLE_NAME,
    BUSINESS_KEY,
    ERROR_TYPE,
    ERROR_MESSAGE,
    LOAD_TIMESTAMP,
    RAW_RECORD
)
SELECT
    'SHIPMENT_PIPELINE',
    'STAGE_TO_CLEAN',
    'STAGE_SHIPMENTS',
    COALESCE(TO_VARCHAR(SHIPMENT_ID),'UNKNOWN'),
    CASE
        WHEN SHIPMENT_ID IS NULL THEN 'NULL_SHIPMENT_ID'
        WHEN ORDER_ID IS NULL THEN 'NULL_ORDER_ID'
        WHEN SHIP_DATE IS NULL THEN 'NULL_SHIP_DATE'
        WHEN DELIVERY_DATE IS NULL THEN 'NULL_DELIVERY_DATE'
        WHEN SHIP_DATE > CURRENT_DATE() THEN 'FUTURE_SHIP_DATE'
        WHEN DELIVERY_DATE > CURRENT_DATE() THEN 'FUTURE_DELIVERY_DATE'
        WHEN DELIVERY_DATE < SHIP_DATE THEN 'INVALID_DELIVERY_SEQUENCE'
        WHEN CARRIER IS NULL OR TRIM(CARRIER) = '' THEN 'INVALID_CARRIER'
        WHEN STATUS IS NULL OR TRIM(STATUS) = '' THEN 'INVALID_STATUS'
    END AS ERROR_TYPE,
    CASE
        WHEN SHIPMENT_ID IS NULL THEN 'SHIPMENT ID IS NULL'
        WHEN ORDER_ID IS NULL THEN 'ORDER ID IS NULL'
        WHEN SHIP_DATE IS NULL THEN 'SHIP DATE IS NULL'
        WHEN DELIVERY_DATE IS NULL THEN 'DELIVERY DATE IS NULL'
        WHEN SHIP_DATE > CURRENT_DATE() THEN 'SHIP DATE CANNOT BE IN FUTURE'
        WHEN DELIVERY_DATE > CURRENT_DATE() THEN 'DELIVERY DATE CANNOT BE IN FUTURE'
        WHEN DELIVERY_DATE < SHIP_DATE THEN 'DELIVERY DATE CANNOT BE BEFORE SHIP DATE'
        WHEN CARRIER IS NULL OR TRIM(CARRIER) = '' THEN 'CARRIER IS NULL OR BLANK'
        WHEN STATUS IS NULL OR TRIM(STATUS) = '' THEN 'STATUS IS NULL OR BLANK'
    END AS ERROR_MESSAGE,
    CURRENT_TIMESTAMP(),
    OBJECT_CONSTRUCT(*)
FROM ECOM_DEV_DB.STAGE.STAGE_SHIPMENTS
WHERE SHIPMENT_ID IS NULL
   OR ORDER_ID IS NULL
   OR SHIP_DATE IS NULL
   OR DELIVERY_DATE IS NULL
   OR SHIP_DATE > CURRENT_DATE()
   OR DELIVERY_DATE > CURRENT_DATE()
   OR DELIVERY_DATE < SHIP_DATE
   OR CARRIER IS NULL OR TRIM(CARRIER) = ''
   OR STATUS IS NULL OR TRIM(STATUS) = '';

-- STEP 1 : STANDARDIZATION + VALIDATION
CREATE OR REPLACE TEMP TABLE TEMP_SHIPMENTS_STEP1 AS
SELECT
    SHIPMENT_ID,
    ORDER_ID,
    SHIP_DATE,
    DELIVERY_DATE,
    UPPER(TRIM(CARRIER)) AS CARRIER,
    UPPER(TRIM(STATUS)) AS STATUS
FROM ECOM_DEV_DB.STAGE.STAGE_SHIPMENTS
WHERE SHIPMENT_ID IS NOT NULL
  AND ORDER_ID IS NOT NULL
  AND SHIP_DATE IS NOT NULL
  AND DELIVERY_DATE IS NOT NULL
  AND CARRIER IS NOT NULL AND TRIM(CARRIER) <> ''
  AND STATUS IS NOT NULL AND TRIM(STATUS) <> ''
  AND SHIP_DATE <= CURRENT_DATE()
  AND DELIVERY_DATE <= CURRENT_DATE()
  AND DELIVERY_DATE >= SHIP_DATE;

-- STEP 1B : EXACT DUPLICATE RECORDS TO DQ
INSERT INTO ECOM_DEV_DB.DQ.DQ_ERROR_LOG
(
    PIPELINE_NAME,
    LAYER_NAME,
    TABLE_NAME,
    BUSINESS_KEY,
    ERROR_TYPE,
    ERROR_MESSAGE,
    LOAD_TIMESTAMP,
    RAW_RECORD
)
SELECT
    'SHIPMENT_PIPELINE',
    'STAGE_TO_CLEAN',
    'STAGE_SHIPMENTS',
    TO_VARCHAR(SHIPMENT_ID),
    'DUPLICATE_SHIPMENT_RECORD',
    'EXACT DUPLICATE SHIPMENT RECORD REMOVED DURING CLEANING',
    CURRENT_TIMESTAMP(),
    OBJECT_CONSTRUCT(*)
FROM (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY SHIPMENT_ID, ORDER_ID, SHIP_DATE, DELIVERY_DATE, CARRIER, STATUS
               ORDER BY DELIVERY_DATE DESC
           ) AS RN
    FROM TEMP_SHIPMENTS_STEP1
) X
WHERE RN > 1;

-- STEP 2 : REMOVE EXACT DUPLICATES
CREATE OR REPLACE TEMP TABLE TEMP_SHIPMENTS_STEP2 AS
SELECT DISTINCT
    SHIPMENT_ID,
    ORDER_ID,
    SHIP_DATE,
    DELIVERY_DATE,
    CARRIER,
    STATUS
FROM TEMP_SHIPMENTS_STEP1;

-- STEP 3 : FIND CONFLICTING SHIPMENT IDS
CREATE OR REPLACE TEMP TABLE TEMP_BAD_SHIPMENT_IDS AS
SELECT SHIPMENT_ID
FROM (
    SELECT SHIPMENT_ID,
           COUNT(*) AS TOTAL_ROWS,
           COUNT(DISTINCT CONCAT_WS('|',ORDER_ID,SHIP_DATE,DELIVERY_DATE,CARRIER,STATUS)) AS UNIQUE_ROWS
    FROM TEMP_SHIPMENTS_STEP2
    GROUP BY SHIPMENT_ID
) X
WHERE TOTAL_ROWS <> UNIQUE_ROWS;

-- STEP 3A : CONFLICTING SHIPMENT IDS TO DQ
INSERT INTO ECOM_DEV_DB.DQ.DQ_ERROR_LOG
(
    PIPELINE_NAME,
    LAYER_NAME,
    TABLE_NAME,
    BUSINESS_KEY,
    ERROR_TYPE,
    ERROR_MESSAGE,
    LOAD_TIMESTAMP,
    RAW_RECORD
)
SELECT
    'SHIPMENT_PIPELINE',
    'STAGE_TO_CLEAN',
    'STAGE_SHIPMENTS',
    TO_VARCHAR(SHIPMENT_ID),
    'CONFLICTING_SHIPMENT_RECORD',
    'SHIPMENT_ID HAS MULTIPLE DIFFERENT ORDER_ID / SHIP_DATE / DELIVERY_DATE / CARRIER / STATUS COMBINATIONS',
    CURRENT_TIMESTAMP(),
    OBJECT_CONSTRUCT(*)
FROM TEMP_SHIPMENTS_STEP2
WHERE SHIPMENT_ID IN (SELECT SHIPMENT_ID FROM TEMP_BAD_SHIPMENT_IDS);

-- STEP 4 : REMOVE CONFLICTING SHIPMENT IDS
CREATE OR REPLACE TEMP TABLE TEMP_SHIPMENTS_FINAL AS
SELECT *
FROM TEMP_SHIPMENTS_STEP2
WHERE SHIPMENT_ID NOT IN (SELECT SHIPMENT_ID FROM TEMP_BAD_SHIPMENT_IDS);

-- STEP 5 : LOAD CLEAN TABLE
INSERT INTO ECOM_DEV_DB.CLEAN.SHIPMENTS_CLEAN
(
    SHIPMENT_ID,
    ORDER_ID,
    SHIP_DATE,
    DELIVERY_DATE,
    CARRIER,
    STATUS
)
SELECT
    SHIPMENT_ID,
    ORDER_ID,
    SHIP_DATE,
    DELIVERY_DATE,
    CARRIER,
    STATUS
FROM TEMP_SHIPMENTS_FINAL;
-- =====================================================================
-- STAGE TO CLEAN : PRODUCTS
-- CLEAN LAYER BUSINESS RULES
-- =====================================================================

-- STEP 1A : INVALID PRODUCT RECORDS TO DQ
INSERT INTO ECOM_DEV_DB.DQ.DQ_ERROR_LOG
(
    PIPELINE_NAME,
    LAYER_NAME,
    TABLE_NAME,
    BUSINESS_KEY,
    ERROR_TYPE,
    ERROR_MESSAGE,
    LOAD_TIMESTAMP,
    RAW_RECORD
)
SELECT
    'PRODUCT_PIPELINE',
    'STAGE_TO_CLEAN',
    'STAGE_PRODUCTS',
    COALESCE(TO_VARCHAR(PRODUCT_ID), 'UNKNOWN'),
    CASE
        WHEN PRODUCT_ID IS NULL THEN 'NULL_PRODUCT_ID'
        WHEN NAME IS NULL OR TRIM(NAME) = '' THEN 'INVALID_PRODUCT_NAME'
        WHEN CATEGORY IS NULL OR TRIM(CATEGORY) = '' THEN 'INVALID_CATEGORY'
        WHEN PRICE IS NULL THEN 'NULL_PRICE'
        WHEN PRICE <= 0 THEN 'INVALID_PRICE'
        WHEN CURRENCY IS NULL OR TRIM(CURRENCY) = '' THEN 'INVALID_CURRENCY'
        WHEN STOCK_QUANTITY IS NULL THEN 'NULL_STOCK_QUANTITY'
        WHEN STOCK_QUANTITY < 0 THEN 'NEGATIVE_STOCK_QUANTITY'
        WHEN SUPPLIER_ID IS NULL THEN 'NULL_SUPPLIER_ID'
        WHEN UPPER(NAME) LIKE '%TEST%' THEN 'TEST_PRODUCT'
        WHEN UPPER(NAME) LIKE '%DUMMY%' THEN 'DUMMY_PRODUCT'
        WHEN UPPER(NAME) LIKE '%SAMPLE%' THEN 'SAMPLE_PRODUCT'
        WHEN UPPER(NAME) LIKE '%UNKNOWN%' THEN 'UNKNOWN_PRODUCT'
    END AS ERROR_TYPE,
    CASE
        WHEN PRODUCT_ID IS NULL THEN 'PRODUCT ID IS NULL'
        WHEN NAME IS NULL OR TRIM(NAME) = '' THEN 'PRODUCT NAME IS NULL OR BLANK'
        WHEN CATEGORY IS NULL OR TRIM(CATEGORY) = '' THEN 'CATEGORY IS NULL OR BLANK'
        WHEN PRICE IS NULL THEN 'PRICE IS NULL'
        WHEN PRICE <= 0 THEN 'PRICE MUST BE GREATER THAN ZERO'
        WHEN CURRENCY IS NULL OR TRIM(CURRENCY) = '' THEN 'CURRENCY IS NULL OR BLANK'
        WHEN STOCK_QUANTITY IS NULL THEN 'STOCK QUANTITY IS NULL'
        WHEN STOCK_QUANTITY < 0 THEN 'STOCK QUANTITY CANNOT BE NEGATIVE'
        WHEN SUPPLIER_ID IS NULL THEN 'SUPPLIER ID IS NULL'
        WHEN UPPER(NAME) LIKE '%TEST%' THEN 'TEST PRODUCT DETECTED'
        WHEN UPPER(NAME) LIKE '%DUMMY%' THEN 'DUMMY PRODUCT DETECTED'
        WHEN UPPER(NAME) LIKE '%SAMPLE%' THEN 'SAMPLE PRODUCT DETECTED'
        WHEN UPPER(NAME) LIKE '%UNKNOWN%' THEN 'UNKNOWN PRODUCT DETECTED'
    END AS ERROR_MESSAGE,
    CURRENT_TIMESTAMP(),
    OBJECT_CONSTRUCT(*)
FROM ECOM_DEV_DB.STAGE.STAGE_PRODUCTS
WHERE PRODUCT_ID IS NULL
   OR NAME IS NULL OR TRIM(NAME) = ''
   OR CATEGORY IS NULL OR TRIM(CATEGORY) = ''
   OR PRICE IS NULL OR PRICE <= 0
   OR CURRENCY IS NULL OR TRIM(CURRENCY) = ''
   OR STOCK_QUANTITY IS NULL OR STOCK_QUANTITY < 0
   OR SUPPLIER_ID IS NULL
   OR UPPER(NAME) LIKE '%TEST%'
   OR UPPER(NAME) LIKE '%DUMMY%'
   OR UPPER(NAME) LIKE '%SAMPLE%'
   OR UPPER(NAME) LIKE '%UNKNOWN%';

-- STEP 1 : STANDARDIZATION + VALIDATION
CREATE OR REPLACE TEMP TABLE TEMP_PRODUCTS_STEP1 AS
SELECT
    PRODUCT_ID,
    REGEXP_REPLACE(UPPER(TRIM(NAME)),'\\s+',' ') AS NAME,
    UPPER(TRIM(CATEGORY)) AS CATEGORY,
    ROUND(PRICE,2) AS PRICE,
    UPPER(TRIM(CURRENCY)) AS CURRENCY,
    STOCK_QUANTITY,
    SUPPLIER_ID
FROM ECOM_DEV_DB.STAGE.STAGE_PRODUCTS
WHERE PRODUCT_ID IS NOT NULL
  AND NAME IS NOT NULL AND TRIM(NAME) <> ''
  AND CATEGORY IS NOT NULL AND TRIM(CATEGORY) <> ''
  AND PRICE IS NOT NULL AND PRICE > 0
  AND CURRENCY IS NOT NULL AND TRIM(CURRENCY) <> ''
  AND STOCK_QUANTITY IS NOT NULL AND STOCK_QUANTITY >= 0
  AND SUPPLIER_ID IS NOT NULL
  AND UPPER(NAME) NOT LIKE '%TEST%'
  AND UPPER(NAME) NOT LIKE '%DUMMY%'
  AND UPPER(NAME) NOT LIKE '%SAMPLE%'
  AND UPPER(NAME) NOT LIKE '%UNKNOWN%';

-- STEP 2A : LOG EXACT DUPLICATE RECORDS TO DQ
INSERT INTO ECOM_DEV_DB.DQ.DQ_ERROR_LOG
(
    PIPELINE_NAME,
    LAYER_NAME,
    TABLE_NAME,
    BUSINESS_KEY,
    ERROR_TYPE,
    ERROR_MESSAGE,
    LOAD_TIMESTAMP,
    RAW_RECORD
)
SELECT
    'PRODUCT_PIPELINE',
    'STAGE_TO_CLEAN',
    'STAGE_PRODUCTS',
    TO_VARCHAR(PRODUCT_ID),
    'DUPLICATE_PRODUCT_RECORD',
    'EXACT DUPLICATE PRODUCT RECORD REMOVED DURING CLEANING',
    CURRENT_TIMESTAMP(),
    OBJECT_CONSTRUCT(*)
FROM (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY PRODUCT_ID, NAME, CATEGORY, PRICE, CURRENCY, STOCK_QUANTITY, SUPPLIER_ID
               ORDER BY PRODUCT_ID
           ) AS RN
    FROM TEMP_PRODUCTS_STEP1
) X
WHERE RN > 1;

-- STEP 2 : REMOVE EXACT DUPLICATES
CREATE OR REPLACE TEMP TABLE TEMP_PRODUCTS_STEP2 AS
SELECT DISTINCT PRODUCT_ID, NAME, CATEGORY, PRICE, CURRENCY, STOCK_QUANTITY, SUPPLIER_ID
FROM TEMP_PRODUCTS_STEP1;

-- STEP 3 : FIND CONFLICTING PRODUCT IDS
CREATE OR REPLACE TEMP TABLE TEMP_BAD_PRODUCT_IDS AS
SELECT PRODUCT_ID
FROM TEMP_PRODUCTS_STEP2
GROUP BY PRODUCT_ID
HAVING COUNT(DISTINCT CONCAT_WS('|',NAME,CATEGORY,PRICE,CURRENCY,STOCK_QUANTITY,SUPPLIER_ID)) > 1;

-- STEP 3A : LOG CONFLICTING PRODUCT IDS TO DQ
INSERT INTO ECOM_DEV_DB.DQ.DQ_ERROR_LOG
(
    PIPELINE_NAME,
    LAYER_NAME,
    TABLE_NAME,
    BUSINESS_KEY,
    ERROR_TYPE,
    ERROR_MESSAGE,
    LOAD_TIMESTAMP,
    RAW_RECORD
)
SELECT 
    'PRODUCT_PIPELINE',
    'STAGE_TO_CLEAN',
    'STAGE_PRODUCTS',
    TO_VARCHAR(PRODUCT_ID),
    'CONFLICTING_PRODUCT_RECORD',
    'PRODUCT_ID HAS MULTIPLE DIFFERENT NAME / CATEGORY / PRICE / CURRENCY / STOCK / SUPPLIER COMBINATIONS',
    CURRENT_TIMESTAMP(),
    OBJECT_CONSTRUCT(*)
FROM TEMP_PRODUCTS_STEP2
WHERE PRODUCT_ID IN (SELECT PRODUCT_ID FROM TEMP_BAD_PRODUCT_IDS);

-- STEP 4 : REMOVE CONFLICTING PRODUCT IDS
CREATE OR REPLACE TEMP TABLE TEMP_PRODUCTS_FINAL AS
SELECT *
FROM TEMP_PRODUCTS_STEP2
WHERE PRODUCT_ID NOT IN (SELECT PRODUCT_ID FROM TEMP_BAD_PRODUCT_IDS);

-- STEP 5 : LOAD CLEAN TABLE
INSERT INTO ECOM_DEV_DB.CLEAN.PRODUCTS_CLEAN
(
    PRODUCT_ID,
    NAME,
    CATEGORY,
    PRICE,
    CURRENCY,
    STOCK_QUANTITY,
    SUPPLIER_ID
)
SELECT PRODUCT_ID, NAME, CATEGORY, PRICE, CURRENCY, STOCK_QUANTITY, SUPPLIER_ID
FROM TEMP_PRODUCTS_FINAL;
-- =====================================================================
-- STAGE TO CLEAN : EMPLOYEES PIPELINE
-- =====================================================================

-- STEP 1A : INVALID EMPLOYEE RECORDS TO DQ
INSERT INTO ECOM_DEV_DB.DQ.DQ_ERROR_LOG
(
    PIPELINE_NAME,
    LAYER_NAME,
    TABLE_NAME,
    BUSINESS_KEY,
    ERROR_TYPE,
    ERROR_MESSAGE,
    LOAD_TIMESTAMP,
    RAW_RECORD
)
SELECT
    'EMPLOYEE_PIPELINE',
    'STAGE_TO_CLEAN',
    'STAGE_EMPLOYEES',
    COALESCE(TO_VARCHAR(EMPLOYEE_ID), 'UNKNOWN'),
    CASE
        WHEN EMPLOYEE_ID IS NULL THEN 'NULL_EMPLOYEE_ID'
        WHEN NAME IS NULL OR TRIM(NAME) = '' THEN 'INVALID_EMPLOYEE_NAME'
        WHEN ROLE IS NULL OR TRIM(ROLE) = '' THEN 'INVALID_ROLE'
        WHEN DEPARTMENT IS NULL OR TRIM(DEPARTMENT) = '' THEN 'INVALID_DEPARTMENT'
        WHEN COUNTRY IS NULL OR TRIM(COUNTRY) = '' THEN 'INVALID_COUNTRY'
        WHEN HIRED_DATE IS NULL THEN 'NULL_HIRED_DATE'
        WHEN HIRED_DATE > CURRENT_DATE() THEN 'FUTURE_HIRED_DATE'
    END AS ERROR_TYPE,
    CASE
        WHEN EMPLOYEE_ID IS NULL THEN 'EMPLOYEE ID IS NULL'
        WHEN NAME IS NULL OR TRIM(NAME) = '' THEN 'EMPLOYEE NAME IS NULL OR BLANK'
        WHEN ROLE IS NULL OR TRIM(ROLE) = '' THEN 'ROLE IS NULL OR BLANK'
        WHEN DEPARTMENT IS NULL OR TRIM(DEPARTMENT) = '' THEN 'DEPARTMENT IS NULL OR BLANK'
        WHEN COUNTRY IS NULL OR TRIM(COUNTRY) = '' THEN 'COUNTRY IS NULL OR BLANK'
        WHEN HIRED_DATE IS NULL THEN 'HIRED DATE IS NULL'
        WHEN HIRED_DATE > CURRENT_DATE() THEN 'HIRED DATE CANNOT BE FUTURE DATE'
    END AS ERROR_MESSAGE,
    CURRENT_TIMESTAMP(),
    OBJECT_CONSTRUCT(*)
FROM ECOM_DEV_DB.STAGE.STAGE_EMPLOYEES
WHERE EMPLOYEE_ID IS NULL
   OR NAME IS NULL OR TRIM(NAME) = ''
   OR ROLE IS NULL OR TRIM(ROLE) = ''
   OR DEPARTMENT IS NULL OR TRIM(DEPARTMENT) = ''
   OR COUNTRY IS NULL OR TRIM(COUNTRY) = ''
   OR HIRED_DATE IS NULL
   OR HIRED_DATE > CURRENT_DATE();

-- STEP 1 : STANDARDIZATION + VALIDATION
CREATE OR REPLACE TEMP TABLE TEMP_EMPLOYEES_STEP1 AS
SELECT
    EMPLOYEE_ID,
    REGEXP_REPLACE(UPPER(TRIM(NAME)),'\\s+',' ') AS NAME,
    UPPER(TRIM(ROLE)) AS ROLE,
    UPPER(TRIM(DEPARTMENT)) AS DEPARTMENT,
    UPPER(TRIM(COUNTRY)) AS COUNTRY,
    HIRED_DATE
FROM ECOM_DEV_DB.STAGE.STAGE_EMPLOYEES
WHERE EMPLOYEE_ID IS NOT NULL
  AND NAME IS NOT NULL AND TRIM(NAME) <> ''
  AND ROLE IS NOT NULL AND TRIM(ROLE) <> ''
  AND DEPARTMENT IS NOT NULL AND TRIM(DEPARTMENT) <> ''
  AND COUNTRY IS NOT NULL AND TRIM(COUNTRY) <> ''
  AND HIRED_DATE IS NOT NULL
  AND HIRED_DATE <= CURRENT_DATE();

-- STEP 2A : LOG EXACT DUPLICATE RECORDS TO DQ
INSERT INTO ECOM_DEV_DB.DQ.DQ_ERROR_LOG
(
    PIPELINE_NAME,
    LAYER_NAME,
    TABLE_NAME,
    BUSINESS_KEY,
    ERROR_TYPE,
    ERROR_MESSAGE,
    LOAD_TIMESTAMP,
    RAW_RECORD
)
SELECT
    'EMPLOYEE_PIPELINE',
    'STAGE_TO_CLEAN',
    'STAGE_EMPLOYEES',
    TO_VARCHAR(EMPLOYEE_ID),
    'DUPLICATE_EMPLOYEE_RECORD',
    'EXACT DUPLICATE EMPLOYEE RECORD REMOVED DURING CLEANING',
    CURRENT_TIMESTAMP(),
    OBJECT_CONSTRUCT(*)
FROM (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY EMPLOYEE_ID, NAME, ROLE, DEPARTMENT, COUNTRY, HIRED_DATE
               ORDER BY EMPLOYEE_ID
           ) AS RN
    FROM TEMP_EMPLOYEES_STEP1
) X
WHERE RN > 1;

-- STEP 2 : REMOVE EXACT DUPLICATES
CREATE OR REPLACE TEMP TABLE TEMP_EMPLOYEES_STEP2 AS
SELECT DISTINCT EMPLOYEE_ID, NAME, ROLE, DEPARTMENT, COUNTRY, HIRED_DATE
FROM TEMP_EMPLOYEES_STEP1;

-- STEP 3 : FIND CONFLICTING EMPLOYEE IDS
CREATE OR REPLACE TEMP TABLE TEMP_BAD_EMPLOYEE_IDS AS
SELECT EMPLOYEE_ID
FROM TEMP_EMPLOYEES_STEP2
GROUP BY EMPLOYEE_ID
HAVING COUNT(DISTINCT CONCAT_WS('|',NAME,ROLE,DEPARTMENT,COUNTRY,HIRED_DATE)) > 1;

-- STEP 3A : LOG CONFLICTING EMPLOYEE IDS TO DQ
INSERT INTO ECOM_DEV_DB.DQ.DQ_ERROR_LOG
(
    PIPELINE_NAME,
    LAYER_NAME,
    TABLE_NAME,
    BUSINESS_KEY,
    ERROR_TYPE,
    ERROR_MESSAGE,
    LOAD_TIMESTAMP,
    RAW_RECORD
)
SELECT
    'EMPLOYEE_PIPELINE',
    'STAGE_TO_CLEAN',
    'STAGE_EMPLOYEES',
    TO_VARCHAR(A.EMPLOYEE_ID),
    'CONFLICTING_EMPLOYEE_RECORD',
    'EMPLOYEE_ID HAS MULTIPLE DIFFERENT NAME / ROLE / DEPARTMENT / COUNTRY / HIRED_DATE VALUES',
    CURRENT_TIMESTAMP(),
    OBJECT_CONSTRUCT(*)
FROM TEMP_EMPLOYEES_STEP2 A
INNER JOIN TEMP_BAD_EMPLOYEE_IDS B ON A.EMPLOYEE_ID = B.EMPLOYEE_ID;

-- STEP 4 : REMOVE CONFLICTING EMPLOYEE IDS
CREATE OR REPLACE TEMP TABLE TEMP_EMPLOYEES_FINAL AS
SELECT *
FROM TEMP_EMPLOYEES_STEP2 A
WHERE NOT EXISTS (
    SELECT 1
    FROM TEMP_BAD_EMPLOYEE_IDS B
    WHERE A.EMPLOYEE_ID = B.EMPLOYEE_ID
);

-- STEP 5 : LOAD CLEAN TABLE
INSERT INTO ECOM_DEV_DB.CLEAN.EMPLOYEES_CLEAN
(
    EMPLOYEE_ID,
    NAME,
    ROLE,
    DEPARTMENT,
    COUNTRY,
    HIRED_DATE
)
SELECT EMPLOYEE_ID, NAME, ROLE, DEPARTMENT, COUNTRY, HIRED_DATE
FROM TEMP_EMPLOYEES_FINAL;