- ============================================================
-- GOLD Layer: Dimension Tables
-- ============================================================

CREATE OR REPLACE TABLE ECOM_DEV_DB.GOLD.DIM_CUSTOMERS (
    DIM_CUSTOMER_KEY INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CUSTOMER_ID INT,
    NAME VARCHAR,
    EMAIL VARCHAR,
    COUNTRY VARCHAR
);

CREATE OR REPLACE TABLE ECOM_DEV_DB.GOLD.DIM_PRODUCTS (
    DIM_PRODUCT_KEY INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRODUCT_ID INT,
    NAME VARCHAR,
    CATEGORY VARCHAR,
    PRICE DECIMAL,
    CURRENCY VARCHAR,
    SUPPLIER_ID INT
);

CREATE OR REPLACE TABLE ECOM_DEV_DB.GOLD.DIM_EMPLOYEES (
    DIM_EMPLOYEE_KEY INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMPLOYEE_ID INT,
    NAME VARCHAR,
    ROLE VARCHAR,
    DEPARTMENT VARCHAR,
    COUNTRY VARCHAR
);

CREATE OR REPLACE TABLE ECOM_DEV_DB.GOLD.DIM_SHIPMENTS (
    DIM_SHIPMENT_KEY INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SHIPMENT_ID INT,
    CARRIER VARCHAR,
    STATUS VARCHAR
);

CREATE OR REPLACE TABLE ECOM_DEV_DB.GOLD.DIM_PAYMENTS (
    DIM_PAYMENT_KEY INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PAYMENT_ID INT,
    PAYMENT_METHOD VARCHAR,
    CURRENCY VARCHAR
);

CREATE OR REPLACE TABLE ECOM_DEV_DB.GOLD.DIM_DATE (
    DIM_DATE_KEY INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATE_ID DATE,
    DAY INT,
    MONTH INT,
    YEAR INT,
    QUARTER INT
);

-- ============================================================
-- GOLD Layer: Fact Tables
-- ============================================================

CREATE OR REPLACE TABLE ECOM_DEV_DB.GOLD.FACT_ORDERS (
    FACT_ORDER_KEY INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DIM_CUSTOMER_KEY INT,
    DIM_DATE_KEY INT,
    TOTAL_AMOUNT DECIMAL,
    STATUS VARCHAR,
    CONSTRAINT FK_FACTORDERS_CUSTOMER FOREIGN KEY (DIM_CUSTOMER_KEY) REFERENCES DIM_CUSTOMERS(DIM_CUSTOMER_KEY),
    CONSTRAINT FK_FACTORDERS_DATE FOREIGN KEY (DIM_DATE_KEY) REFERENCES DIM_DATE(DIM_DATE_KEY)
);

CREATE OR REPLACE TABLE ECOM_DEV_DB.GOLD.FACT_ORDER_PRODUCTS (
    FACT_ORDER_PRODUCT_KEY INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FACT_ORDER_KEY INT,
    DIM_PRODUCT_KEY INT,
    QUANTITY INT,
    LINE_AMOUNT DECIMAL,
    CONSTRAINT FK_FACTORDERPRODUCT_ORDER FOREIGN KEY (FACT_ORDER_KEY) REFERENCES FACT_ORDERS(FACT_ORDER_KEY),
    CONSTRAINT FK_FACTORDERPRODUCT_PRODUCT FOREIGN KEY (DIM_PRODUCT_KEY) REFERENCES DIM_PRODUCTS(DIM_PRODUCT_KEY)
);

CREATE OR REPLACE TABLE ECOM_DEV_DB.GOLD.FACT_PAYMENTS (
    FACT_PAYMENT_KEY INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DIM_PAYMENT_KEY INT,
    DIM_DATE_KEY INT,
    AMOUNT DECIMAL,
    CONSTRAINT FK_FACTPAYMENTS_PAYMENT FOREIGN KEY (DIM_PAYMENT_KEY) REFERENCES DIM_PAYMENTS(DIM_PAYMENT_KEY),
    CONSTRAINT FK_FACTPAYMENTS_DATE FOREIGN KEY (DIM_DATE_KEY) REFERENCES DIM_DATE(DIM_DATE_KEY)
);

CREATE OR REPLACE TABLE ECOM_DEV_DB.GOLD.FACT_SHIPMENTS (
    FACT_SHIPMENT_KEY INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DIM_SHIPMENT_KEY INT,
    DIM_DATE_KEY INT,
    DELIVERY_DATE DATE,
    STATUS VARCHAR,
    CONSTRAINT FK_FACTSHIPMENTS_SHIPMENT FOREIGN KEY (DIM_SHIPMENT_KEY) REFERENCES DIM_SHIPMENTS(DIM_SHIPMENT_KEY),
    CONSTRAINT FK_FACTSHIPMENTS_DATE FOREIGN KEY (DIM_DATE_KEY) REFERENCES DIM_DATE(DIM_DATE_KEY)
);

CREATE OR REPLACE TABLE ECOM_DEV_DB.GOLD.FACT_SALES (
    FACT_SALE_KEY INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DIM_PRODUCT_KEY INT,
    DIM_CUSTOMER_KEY INT,
    DIM_DATE_KEY INT,
    REVENUE DECIMAL,
    DISCOUNT DECIMAL,
    PROFIT DECIMAL,
    CONSTRAINT FK_FACTSALES_PRODUCT FOREIGN KEY (DIM_PRODUCT_KEY) REFERENCES DIM_PRODUCTS(DIM_PRODUCT_KEY),
    CONSTRAINT FK_FACTSALES_CUSTOMER FOREIGN KEY (DIM_CUSTOMER_KEY) REFERENCES DIM_CUSTOMERS(DIM_CUSTOMER_KEY),
    CONSTRAINT FK_FACTSALES_DATE FOREIGN KEY (DIM_DATE_KEY) REFERENCES DIM_DATE(DIM_DATE_KEY)
);

CREATE OR REPLACE TABLE ECOM_DEV_DB.GOLD.FACT_EMPLOYEE_ACTIVITY (
    FACT_ACTIVITY_KEY INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DIM_EMPLOYEE_KEY INT,
    DIM_DATE_KEY INT,
    ORDERS_HANDLED INT,
    SHIPMENTS_PROCESSED INT,
    CONSTRAINT FK_FACTEMPLOYEE_EMP FOREIGN KEY (DIM_EMPLOYEE_KEY) REFERENCES DIM_EMPLOYEES(DIM_EMPLOYEE_KEY),
    CONSTRAINT FK_FACTEMPLOYEE_DATE FOREIGN KEY (DIM_DATE_KEY) REFERENCES DIM_DATE(DIM_DATE_KEY)
);