
-- test from STAGE to clean 2 #####################################################################################################
CREATE OR REPLACE VIEW ECOM_DEV_DB.TEST.VW_STAGE_CUSTOMERS_VALIDATION AS
SELECT
    S.*,
    CASE WHEN CUSTOMER_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS CUSTOMER_ID_CHECK,
    CASE WHEN EMAIL IS NULL OR NOT REGEXP_LIKE(EMAIL,'^[^@]+@[^@]+\.[^@]+$') THEN 'FAIL' ELSE 'PASS' END AS EMAIL_CHECK,
    CASE WHEN CREATED_AT IS NULL OR CREATED_AT > CURRENT_DATE() THEN 'FAIL' ELSE 'PASS' END AS CREATED_AT_CHECK,
    CASE WHEN COUNT(*) OVER (PARTITION BY CUSTOMER_ID) > 1 THEN 'FAIL' ELSE 'PASS' END AS DUPLICATE_ID_CHECK
FROM ECOM_DEV_DB.STAGE.STAGE_CUSTOMERS S;
CREATE OR REPLACE VIEW ECOM_DEV_DB.TEST.VW_STAGE_PRODUCTS_VALIDATION AS
SELECT
    S.*,
    CASE WHEN PRODUCT_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS PRODUCT_ID_CHECK,
    CASE WHEN PRICE IS NULL OR PRICE < 0 THEN 'FAIL' ELSE 'PASS' END AS PRICE_CHECK,
    CASE WHEN STOCK_QUANTITY IS NULL OR STOCK_QUANTITY < 0 THEN 'FAIL' ELSE 'PASS' END AS STOCK_CHECK,
    CASE WHEN COUNT(*) OVER (PARTITION BY PRODUCT_ID) > 1 THEN 'FAIL' ELSE 'PASS' END AS DUPLICATE_ID_CHECK
FROM ECOM_DEV_DB.STAGE.STAGE_PRODUCTS S;
CREATE OR REPLACE VIEW ECOM_DEV_DB.TEST.VW_STAGE_EMPLOYEES_VALIDATION AS
SELECT
    S.*,
    CASE WHEN EMPLOYEE_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS EMPLOYEE_ID_CHECK,
    CASE WHEN HIRED_DATE IS NULL OR HIRED_DATE > CURRENT_DATE() THEN 'FAIL' ELSE 'PASS' END AS HIRED_DATE_CHECK,
    CASE WHEN ROLE IS NULL OR TRIM(ROLE) = '' THEN 'FAIL' ELSE 'PASS' END AS ROLE_CHECK,
    CASE WHEN COUNT(*) OVER (PARTITION BY EMPLOYEE_ID) > 1 THEN 'FAIL' ELSE 'PASS' END AS DUPLICATE_ID_CHECK
FROM ECOM_DEV_DB.STAGE.STAGE_EMPLOYEES S;
CREATE OR REPLACE VIEW ECOM_DEV_DB.TEST.VW_STAGE_ORDERS_VALIDATION AS
SELECT
    S.*,
    CASE WHEN ORDER_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS ORDER_ID_CHECK,
    CASE WHEN CUSTOMER_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS CUSTOMER_ID_CHECK,
    CASE WHEN TOTAL_AMOUNT IS NULL OR TOTAL_AMOUNT < 0 THEN 'FAIL' ELSE 'PASS' END AS TOTAL_AMOUNT_CHECK,
    CASE WHEN ORDER_DATE IS NULL OR ORDER_DATE > CURRENT_DATE() THEN 'FAIL' ELSE 'PASS' END AS ORDER_DATE_CHECK,
    CASE WHEN COUNT(*) OVER (PARTITION BY ORDER_ID) > 1 THEN 'FAIL' ELSE 'PASS' END AS DUPLICATE_ID_CHECK,
    CASE WHEN C.CUSTOMER_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS CUSTOMER_EXISTS_CHECK
FROM ECOM_DEV_DB.STAGE.STAGE_ORDERS S
LEFT JOIN ECOM_DEV_DB.CLEAN.CUSTOMERS_CLEAN C
    ON S.CUSTOMER_ID = C.CUSTOMER_ID;
    CREATE OR REPLACE VIEW ECOM_DEV_DB.TEST.VW_STAGE_PAYMENTS_VALIDATION AS
SELECT
    S.*,
    CASE WHEN PAYMENT_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS PAYMENT_ID_CHECK,
    CASE WHEN ORDER_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS ORDER_ID_CHECK,
    CASE WHEN AMOUNT IS NULL OR AMOUNT < 0 THEN 'FAIL' ELSE 'PASS' END AS AMOUNT_CHECK,
    CASE WHEN PAYMENT_DATE IS NULL OR PAYMENT_DATE > CURRENT_DATE() THEN 'FAIL' ELSE 'PASS' END AS PAYMENT_DATE_CHECK,
    CASE WHEN COUNT(*) OVER (PARTITION BY PAYMENT_ID) > 1 THEN 'FAIL' ELSE 'PASS' END AS DUPLICATE_ID_CHECK,
    CASE WHEN O.ORDER_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS ORDER_EXISTS_CHECK
FROM ECOM_DEV_DB.STAGE.STAGE_PAYMENTS S
LEFT JOIN ECOM_DEV_DB.CLEAN.ORDERS_CLEAN O
    ON S.ORDER_ID = O.ORDER_ID;
    CREATE OR REPLACE VIEW ECOM_DEV_DB.TEST.VW_STAGE_SHIPMENTS_VALIDATION AS
SELECT
    S.*,
    CASE WHEN SHIPMENT_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS SHIPMENT_ID_CHECK,
    CASE WHEN ORDER_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS ORDER_ID_CHECK,
    CASE WHEN SHIP_DATE IS NULL OR SHIP_DATE > CURRENT_DATE() THEN 'FAIL' ELSE 'PASS' END AS SHIP_DATE_CHECK,
    CASE WHEN DELIVERY_DATE IS NULL OR DELIVERY_DATE < SHIP_DATE THEN 'FAIL' ELSE 'PASS' END AS DELIVERY_DATE_CHECK,
    CASE WHEN COUNT(*) OVER (PARTITION BY SHIPMENT_ID) > 1 THEN 'FAIL' ELSE 'PASS' END AS DUPLICATE_ID_CHECK,
    CASE WHEN O.ORDER_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS ORDER_EXISTS_CHECK
FROM ECOM_DEV_DB.STAGE.STAGE_SHIPMENTS S
LEFT JOIN ECOM_DEV_DB.CLEAN.ORDERS_CLEAN O
    ON S.ORDER_ID = O.ORDER_ID;